version: "3.4"

services:
  db:
    build:
      context: ./docker
      dockerfile: postgres.Dockerfile
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  
  # fimsprotoms:
  #   image: fimsprotoms
  #   build:
  #     context: .
  #     dockerfile: ./docker/Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - GIN_MODE=debug
  #     - PROFILE=dev-docker
  #   depends_on: 
  #     - db
