version: "3.4"

services:
  # fimsprotoms:
  #   image: fimsprotoms
  #   build:
  #     context: .
  #     dockerfile: ./docker/app/Dockerfile
  #   ports:
  #     - 3000:3000
  #   environment:
  #     - GIN_MODE=debug
  #     - PROFILE=dev-docker
  #   depends_on: 
  #     - db

  db:
    build:
      context: ./docker/postgres
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
  
  kratos-migrate:
      image: oryd/kratos:latest
      environment:
        - DSN=postgres://93fe5029-1886-4b63-94ca-35c503a52eff:hePrAqafu&5Ep49V8th9@db:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4&TimeZone=UTC
      volumes:
        - type: bind
          source: ./docker/kratos
          target: /etc/config/kratos
      command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
      restart: on-failure

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:latest
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://93fe5029-1886-4b63-94ca-35c503a52eff:hePrAqafu&5Ep49V8th9@db:5432/postgres?sslmode=disable&max_conns=20&max_idle_conns=4&TimeZone=UTC
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - type: bind
        source: ./docker/kratos
        target: /etc/config/kratos

  # mail server, test purpose
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'