/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	http_port "github/fims-proto/fims-proto-ms/internal/voucher/port/public/http"
)

func main() {
	log.Printf("Server started")

	VoucherApiService := http_port.NewVoucherApiService()
	VoucherApiController := http_port.NewVoucherApiController(VoucherApiService)

	router := http_port.NewRouter(VoucherApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
