/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"

	http "github.com/GIT_USER_ID/GIT_REPO_ID/http"
)

func main() {
	log.Printf("Server started")

	VoucherApiService := http.NewVoucherApiService()
	VoucherApiController := http.NewVoucherApiController(VoucherApiService)

	router := http.NewRouter(VoucherApiController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
