/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http_port

import (
	"context"
	"net/http"
)



// VoucherApiRouter defines the required methods for binding the api requests to a responses for the VoucherApi
// The VoucherApiRouter implementation should parse necessary information from the http request, 
// pass the data to a VoucherApiServicer to perform the required actions, then write the service results to the http response.
type VoucherApiRouter interface { 
	AllVouchers(http.ResponseWriter, *http.Request)
	Audit(http.ResponseWriter, *http.Request)
	RecordVouchers(http.ResponseWriter, *http.Request)
	Review(http.ResponseWriter, *http.Request)
	Update(http.ResponseWriter, *http.Request)
	VoucherForUUID(http.ResponseWriter, *http.Request)
}


// VoucherApiServicer defines the api actions for the VoucherApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type VoucherApiServicer interface { 
	AllVouchers(context.Context) (ImplResponse, error)
	Audit(context.Context, string, PostTraining) (ImplResponse, error)
	RecordVouchers(context.Context, PostTraining) (ImplResponse, error)
	Review(context.Context, string, PostTraining) (ImplResponse, error)
	Update(context.Context, string, PostTraining) (ImplResponse, error)
	VoucherForUUID(context.Context, string) (ImplResponse, error)
}
