/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"context"
	"net/http"
)



// VoucherApiRouter defines the required methods for binding the api requests to a responses for the VoucherApi
// The VoucherApiRouter implementation should parse necessary information from the http request, 
// pass the data to a VoucherApiServicer to perform the required actions, then write the service results to the http response.
type VoucherApiRouter interface { 
	AllVouchers(http.ResponseWriter, *http.Request)
	ApproveRescheduleTraining(http.ResponseWriter, *http.Request)
	CancelTraining(http.ResponseWriter, *http.Request)
	CreateTraining(http.ResponseWriter, *http.Request)
	RejectRescheduleTraining(http.ResponseWriter, *http.Request)
	RequestRescheduleTraining(http.ResponseWriter, *http.Request)
	RescheduleTraining(http.ResponseWriter, *http.Request)
}


// VoucherApiServicer defines the api actions for the VoucherApi service
// This interface intended to stay up to date with the openapi yaml used to generate it, 
// while the service implementation can ignored with the .openapi-generator-ignore file 
// and updated with the logic required for the API.
type VoucherApiServicer interface { 
	AllVouchers(context.Context) (ImplResponse, error)
	ApproveRescheduleTraining(context.Context, string) (ImplResponse, error)
	CancelTraining(context.Context, string) (ImplResponse, error)
	CreateTraining(context.Context, PostTraining) (ImplResponse, error)
	RejectRescheduleTraining(context.Context, string) (ImplResponse, error)
	RequestRescheduleTraining(context.Context, string, PostTraining) (ImplResponse, error)
	RescheduleTraining(context.Context, string, PostTraining) (ImplResponse, error)
}
