/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http_port

import (
	"context"
	"net/http"
	"errors"
)

// VoucherApiService is a service that implents the logic for the VoucherApiServicer
// This service should implement the business logic for every endpoint for the VoucherApi API. 
// Include any external packages or services that will be required by this service.
type VoucherApiService struct {
}

// NewVoucherApiService creates a default api service
func NewVoucherApiService() VoucherApiServicer {
	return &VoucherApiService{}
}

// AllVouchers - 
func (s *VoucherApiService) AllVouchers(ctx context.Context) (ImplResponse, error) {
	// TODO - update AllVouchers with the required logic for this service method.
	// Add api_voucher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Trainings{}) or use other options such as http.Ok ...
	//return Response(200, Trainings{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("AllVouchers method not implemented")
}

// Audit - 
func (s *VoucherApiService) Audit(ctx context.Context, voucherUUID string, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update Audit with the required logic for this service method.
	// Add api_voucher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Audit method not implemented")
}

// RecordVouchers - 
func (s *VoucherApiService) RecordVouchers(ctx context.Context, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update RecordVouchers with the required logic for this service method.
	// Add api_voucher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RecordVouchers method not implemented")
}

// Review - 
func (s *VoucherApiService) Review(ctx context.Context, voucherUUID string, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update Review with the required logic for this service method.
	// Add api_voucher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Review method not implemented")
}

// Update - 
func (s *VoucherApiService) Update(ctx context.Context, voucherUUID string, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update Update with the required logic for this service method.
	// Add api_voucher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("Update method not implemented")
}

// VoucherForUUID - 
func (s *VoucherApiService) VoucherForUUID(ctx context.Context, voucherUUID string) (ImplResponse, error) {
	// TODO - update VoucherForUUID with the required logic for this service method.
	// Add api_voucher_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("VoucherForUUID method not implemented")
}

