/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http_port

import (
	"net/http"
    "github/fims-proto/fims-proto-ms/internal/voucher/app"
	"github/fims-proto/fims-proto-ms/internal/voucher/app/command"
	"github.com/gin-gonic/gin"
)

type Handler struct {
	app app.Application
}

func NewHandler(app app.Application) Handler {
	return Handler{app: app}
}




// AllVouchers - 
func (h Handler) AllVouchers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}


// Audit - 
func (h Handler) Audit(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}


// RecordVouchers - 
func (h Handler) RecordVouchers(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}


// Review - 
func (h Handler) Review(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}


// Update - 
func (h Handler) Update(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}


// VoucherForUUID - 
func (h Handler) VoucherForUUID(c *gin.Context) {
	c.JSON(http.StatusOK, gin.H{})
}