/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implents the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API. 
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// ApproveRescheduleTraining - 
func (s *DefaultApiService) ApproveRescheduleTraining(ctx context.Context, trainingUUID string) (ImplResponse, error) {
	// TODO - update ApproveRescheduleTraining with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("ApproveRescheduleTraining method not implemented")
}

// CancelTraining - 
func (s *DefaultApiService) CancelTraining(ctx context.Context, trainingUUID string) (ImplResponse, error) {
	// TODO - update CancelTraining with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CancelTraining method not implemented")
}

// CreateTraining - 
func (s *DefaultApiService) CreateTraining(ctx context.Context, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update CreateTraining with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateTraining method not implemented")
}

// GetTrainings - 
func (s *DefaultApiService) GetTrainings(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetTrainings with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, Trainings{}) or use other options such as http.Ok ...
	//return Response(200, Trainings{}), nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetTrainings method not implemented")
}

// RejectRescheduleTraining - 
func (s *DefaultApiService) RejectRescheduleTraining(ctx context.Context, trainingUUID string) (ImplResponse, error) {
	// TODO - update RejectRescheduleTraining with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RejectRescheduleTraining method not implemented")
}

// RequestRescheduleTraining - 
func (s *DefaultApiService) RequestRescheduleTraining(ctx context.Context, trainingUUID string, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update RequestRescheduleTraining with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RequestRescheduleTraining method not implemented")
}

// RescheduleTraining - 
func (s *DefaultApiService) RescheduleTraining(ctx context.Context, trainingUUID string, postTraining PostTraining) (ImplResponse, error) {
	// TODO - update RescheduleTraining with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(204, {}) or use other options such as http.Ok ...
	//return Response(204, nil),nil

	//TODO: Uncomment the next line to return response Response(0, Error{}) or use other options such as http.Ok ...
	//return Response(0, Error{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("RescheduleTraining method not implemented")
}

