/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

import (
	"encoding/json"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

// A VoucherApiController binds http requests to an api service and writes the service results to the http response
type VoucherApiController struct {
	service VoucherApiServicer
}

// NewVoucherApiController creates a default api controller
func NewVoucherApiController(s VoucherApiServicer) Router {
	return &VoucherApiController{ service: s }
}

// Routes returns all of the api route for the VoucherApiController
func (c *VoucherApiController) Routes() Routes {
	return Routes{ 
		{
			"AllVouchers",
			strings.ToUpper("Get"),
			"/api/trainings",
			c.AllVouchers,
		},
		{
			"ApproveRescheduleTraining",
			strings.ToUpper("Put"),
			"/api/trainings/{trainingUUID}/approve-reschedule",
			c.ApproveRescheduleTraining,
		},
		{
			"CancelTraining",
			strings.ToUpper("Delete"),
			"/api/trainings/{trainingUUID}",
			c.CancelTraining,
		},
		{
			"CreateTraining",
			strings.ToUpper("Post"),
			"/api/trainings",
			c.CreateTraining,
		},
		{
			"RejectRescheduleTraining",
			strings.ToUpper("Put"),
			"/api/trainings/{trainingUUID}/reject-reschedule",
			c.RejectRescheduleTraining,
		},
		{
			"RequestRescheduleTraining",
			strings.ToUpper("Put"),
			"/api/trainings/{trainingUUID}/request-reschedule",
			c.RequestRescheduleTraining,
		},
		{
			"RescheduleTraining",
			strings.ToUpper("Put"),
			"/api/trainings/{trainingUUID}/reschedule",
			c.RescheduleTraining,
		},
	}
}

// AllVouchers - 
func (c *VoucherApiController) AllVouchers(w http.ResponseWriter, r *http.Request) { 
	result, err := c.service.AllVouchers(r.Context())
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// ApproveRescheduleTraining - 
func (c *VoucherApiController) ApproveRescheduleTraining(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	trainingUUID := params["trainingUUID"]
	result, err := c.service.ApproveRescheduleTraining(r.Context(), trainingUUID)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// CancelTraining - 
func (c *VoucherApiController) CancelTraining(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	trainingUUID := params["trainingUUID"]
	result, err := c.service.CancelTraining(r.Context(), trainingUUID)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// CreateTraining - 
func (c *VoucherApiController) CreateTraining(w http.ResponseWriter, r *http.Request) { 
	postTraining := &PostTraining{}
	if err := json.NewDecoder(r.Body).Decode(&postTraining); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.CreateTraining(r.Context(), *postTraining)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// RejectRescheduleTraining - 
func (c *VoucherApiController) RejectRescheduleTraining(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	trainingUUID := params["trainingUUID"]
	result, err := c.service.RejectRescheduleTraining(r.Context(), trainingUUID)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// RequestRescheduleTraining - 
func (c *VoucherApiController) RequestRescheduleTraining(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	trainingUUID := params["trainingUUID"]
	postTraining := &PostTraining{}
	if err := json.NewDecoder(r.Body).Decode(&postTraining); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.RequestRescheduleTraining(r.Context(), trainingUUID, *postTraining)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}

// RescheduleTraining - 
func (c *VoucherApiController) RescheduleTraining(w http.ResponseWriter, r *http.Request) { 
	params := mux.Vars(r)
	trainingUUID := params["trainingUUID"]
	postTraining := &PostTraining{}
	if err := json.NewDecoder(r.Body).Decode(&postTraining); err != nil {
		w.WriteHeader(http.StatusBadRequest)
		return
	}
	
	result, err := c.service.RescheduleTraining(r.Context(), trainingUUID, *postTraining)
	//If an error occured, encode the error with the status code
	if err != nil {
		EncodeJSONResponse(err.Error(), &result.Code, w)
		return
	}
	//If no error, encode the body and the result code
	EncodeJSONResponse(result.Body, &result.Code, w)
	
}
