/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http_port

//Response return a ImplResponse struct filled
func Response(code int, body interface{}) ImplResponse {
	return ImplResponse{Code: code, Body: body}
}

