/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

//Implementation response defines an error code with the associated body
type ImplResponse struct {
	Code int
	Body interface{}
}