/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http

type Trainings struct {

	Trainings []Training `json:"trainings"`
}
