/*
 * fims-proto vouchers
 *
 * HTTP port generated from openapi v3
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 * Do not modify
 */
package http

import (
	"time"
)

type Training struct {

	Uuid string `json:"uuid"`

	User string `json:"user"`

	UserUuid string `json:"userUuid"`

	Notes string `json:"notes"`

	Time time.Time `json:"time"`

	CanBeCancelled bool `json:"canBeCancelled"`

	MoveRequiresAccept bool `json:"moveRequiresAccept"`

	ProposedTime time.Time `json:"proposedTime,omitempty"`

	MoveProposedBy string `json:"moveProposedBy,omitempty"`
}
