/*
 * fims-proto vouchers
 *
 * HTTP port generated from openapi v3
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 * Do not modify
 */
package http

type Error struct {

	Slug string `json:"slug"`

	Message string `json:"message"`
}
