/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http_port

import (
	"time"
)

type PostTraining struct {

	Notes string `json:"notes"`

	Time time.Time `json:"time"`
}
