/*
 * Wild Workouts trainings
 *
 * TODO
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package http_port

type Error struct {

	Slug string `json:"slug"`

	Message string `json:"message"`
}
