/*
 * fims-proto vouchers
 *
 * HTTP port generated from openapi v3
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 * Do not modify
 */
package http

type LineItemQry struct {

	Summary string `json:"Summary,omitempty"`

	AccountNumber string `json:"AccountNumber,omitempty"`

	Debit string `json:"Debit,omitempty"`

	Credit string `json:"Credit,omitempty"`
}
