/*
 * fims-proto vouchers
 *
 * HTTP port generated from openapi v3
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 * Do not modify
 */
package http

import (
	"time"
)

type RecordVoucherCmd struct {

	UUID string `json:"UUID,omitempty"`

	Number int32 `json:"Number,omitempty"`

	CreatedAt time.Time `json:"CreatedAt,omitempty"`

	AttachmentQuantity int32 `json:"AttachmentQuantity,omitempty"`

	LineItems []LineItemCmd `json:"LineItems,omitempty"`

	Debit string `json:"Debit,omitempty"`

	Credit string `json:"Credit,omitempty"`

	CreatorUUID string `json:"CreatorUUID,omitempty"`
}
