// Package http provides primitives to interact the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package http

import (
	"time"
)

// AuditVoucherCmd defines model for AuditVoucherCmd.
type AuditVoucherCmd struct {
	AuditorUUID string `json:"AuditorUUID"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// LineItemCmd defines model for LineItemCmd.
type LineItemCmd struct {
	AccountNumber string `json:"AccountNumber"`
	Credit        string `json:"Credit"`
	Debit         string `json:"Debit"`
	Summary       string `json:"Summary"`
}

// LineItemQry defines model for LineItemQry.
type LineItemQry struct {
	AccountNumber string `json:"AccountNumber"`
	Credit        string `json:"Credit"`
	Debit         string `json:"Debit"`
	Summary       string `json:"Summary"`
}

// RecordVoucherCmd defines model for RecordVoucherCmd.
type RecordVoucherCmd struct {
	AttachmentQuantity int           `json:"AttachmentQuantity"`
	CreatedAt          time.Time     `json:"CreatedAt"`
	CreatorUUID        string        `json:"CreatorUUID"`
	LineItems          []LineItemCmd `json:"LineItems"`
	Number             *string       `json:"Number,omitempty"`
	UUID               string        `json:"UUID"`
}

// ReviewVoucherCmd defines model for ReviewVoucherCmd.
type ReviewVoucherCmd struct {
	ReviewerUUID string `json:"ReviewerUUID"`
}

// UpdateVoucherCmd defines model for UpdateVoucherCmd.
type UpdateVoucherCmd struct {
	LineItems []LineItemCmd `json:"LineItems"`
}

// VoucherQry defines model for VoucherQry.
type VoucherQry struct {
	AttachmentQuantity int           `json:"AttachmentQuantity"`
	AuditorUUID        string        `json:"AuditorUUID"`
	CreatedAt          time.Time     `json:"CreatedAt"`
	CreatorUUID        string        `json:"CreatorUUID"`
	Credit             string        `json:"Credit"`
	Debit              string        `json:"Debit"`
	IsAudited          bool          `json:"IsAudited"`
	IsReviewed         bool          `json:"IsReviewed"`
	LineItems          []LineItemQry `json:"LineItems"`
	Number             string        `json:"Number"`
	ReviewerUUID       string        `json:"ReviewerUUID"`
	UUID               string        `json:"UUID"`
}

// VouchersQry defines model for VouchersQry.
type VouchersQry []VoucherQry

// RecordJSONBody defines parameters for Record.
type RecordJSONBody RecordVoucherCmd

// UpdateJSONBody defines parameters for Update.
type UpdateJSONBody UpdateVoucherCmd

// AuditJSONBody defines parameters for Audit.
type AuditJSONBody AuditVoucherCmd

// ReviewJSONBody defines parameters for Review.
type ReviewJSONBody ReviewVoucherCmd

// RecordRequestBody defines body for Record for application/json ContentType.
type RecordJSONRequestBody RecordJSONBody

// UpdateRequestBody defines body for Update for application/json ContentType.
type UpdateJSONRequestBody UpdateJSONBody

// AuditRequestBody defines body for Audit for application/json ContentType.
type AuditJSONRequestBody AuditJSONBody

// ReviewRequestBody defines body for Review for application/json ContentType.
type ReviewJSONRequestBody ReviewJSONBody
