// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package http

import (
	"time"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// AuditVoucherRequest defines model for AuditVoucherRequest.
type AuditVoucherRequest struct {
	Auditor string `json:"Auditor"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// LineItemRequest defines model for LineItemRequest.
type LineItemRequest struct {
	AccountNumber string `json:"AccountNumber"`
	Credit        string `json:"Credit"`
	Debit         string `json:"Debit"`
	Id            string `json:"Id"`
	Summary       string `json:"Summary"`
}

// LineItemResponse defines model for LineItemResponse.
type LineItemResponse struct {
	AccountNumber string `json:"AccountNumber"`
	Credit        string `json:"Credit"`
	Debit         string `json:"Debit"`
	Id            string `json:"Id"`
	Summary       string `json:"Summary"`
}

// RecordVoucherRequest defines model for RecordVoucherRequest.
type RecordVoucherRequest struct {
	AttachmentQuantity int               `json:"AttachmentQuantity"`
	Creator            string            `json:"Creator"`
	LineItems          []LineItemRequest `json:"LineItems"`
	VoucherType        string            `json:"VoucherType"`
}

// ReviewVoucherRequest defines model for ReviewVoucherRequest.
type ReviewVoucherRequest struct {
	Reviewer string `json:"Reviewer"`
}

// UpdateVoucherRequest defines model for UpdateVoucherRequest.
type UpdateVoucherRequest struct {
	LineItems []LineItemRequest `json:"LineItems"`
}

// VoucherResponse defines model for VoucherResponse.
type VoucherResponse struct {
	AttachmentQuantity int                `json:"AttachmentQuantity"`
	Auditor            string             `json:"Auditor"`
	CreatedAt          time.Time          `json:"CreatedAt"`
	Creator            string             `json:"Creator"`
	Credit             string             `json:"Credit"`
	Debit              string             `json:"Debit"`
	Id                 string             `json:"Id"`
	IsAudited          bool               `json:"IsAudited"`
	IsPosted           bool               `json:"IsPosted"`
	IsReviewed         bool               `json:"IsReviewed"`
	LineItems          []LineItemResponse `json:"LineItems"`
	Number             string             `json:"Number"`
	Reviewer           string             `json:"Reviewer"`
	Sob                string             `json:"Sob"`
	Type               string             `json:"Type"`
}

// VouchersResponse defines model for VouchersResponse.
type VouchersResponse []VoucherResponse

// RecordJSONBody defines parameters for Record.
type RecordJSONBody RecordVoucherRequest

// UpdateJSONBody defines parameters for Update.
type UpdateJSONBody UpdateVoucherRequest

// AuditJSONBody defines parameters for Audit.
type AuditJSONBody AuditVoucherRequest

// CancelAuditJSONBody defines parameters for CancelAudit.
type CancelAuditJSONBody AuditVoucherRequest

// CancelReviewJSONBody defines parameters for CancelReview.
type CancelReviewJSONBody ReviewVoucherRequest

// ReviewJSONBody defines parameters for Review.
type ReviewJSONBody ReviewVoucherRequest

// RecordJSONRequestBody defines body for Record for application/json ContentType.
type RecordJSONRequestBody RecordJSONBody

// UpdateJSONRequestBody defines body for Update for application/json ContentType.
type UpdateJSONRequestBody UpdateJSONBody

// AuditJSONRequestBody defines body for Audit for application/json ContentType.
type AuditJSONRequestBody AuditJSONBody

// CancelAuditJSONRequestBody defines body for CancelAudit for application/json ContentType.
type CancelAuditJSONRequestBody CancelAuditJSONBody

// CancelReviewJSONRequestBody defines body for CancelReview for application/json ContentType.
type CancelReviewJSONRequestBody CancelReviewJSONBody

// ReviewJSONRequestBody defines body for Review for application/json ContentType.
type ReviewJSONRequestBody ReviewJSONBody
