/*
 * fims-proto vouchers
 *
 * HTTP port generated from openapi v3
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 * Do not modify
 */
package http

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func InitRouter(h Handler, router *gin.Engine) {
    var routes = []Route{
        
        {
            "AllVouchers",
            http.MethodGet,
            "/vouchers/",
            h.AllVouchers,
        },
        {
            "Audit",
            http.MethodPost,
            "/vouchers/:uuid/audit",
            h.Audit,
        },
        {
            "Record",
            http.MethodPost,
            "/vouchers/",
            h.Record,
        },
        {
            "Review",
            http.MethodPost,
            "/vouchers/:uuid/review",
            h.Review,
        },
        {
            "Update",
            http.MethodPatch,
            "/vouchers/:uuid",
            h.Update,
        },
        {
            "VoucherForUUID",
            http.MethodGet,
            "/vouchers/:uuid",
            h.VoucherForUUID,
        },
    }
	for _, route := range routes {
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
        case http.MethodPatch:
            router.PATCH(route.Pattern, route.HandlerFunc)
		}
	}
}

