/*
 * fims-proto vouchers
 *
 * HTTP port generated from openapi v3
 *
 * API version: 1.0.0
 * Contact: xld704@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 * Do not modify
 */
package http

import (
    "strings"
	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name        string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method      string
	// Pattern is the pattern of the URI.
	Pattern     string
	// HandlerFunc is the handler function of this route.
	HandlerFunc gin.HandlerFunc
}

// NewRouter returns a new router.
func InitRouter(h Handler, r *gin.Engine) {
    g := r.Group("/vouchers")
    
    g.Handle(strings.ToUpper("Get"),"/",h.AllVouchers)
    
    g.Handle(strings.ToUpper("Post"),"/:uuid/audit",h.Audit)
    
    g.Handle(strings.ToUpper("Post"),"/",h.Record)
    
    g.Handle(strings.ToUpper("Post"),"/:uuid/review",h.Review)
    
    g.Handle(strings.ToUpper("Patch"),"/:uuid",h.Update)
    
    g.Handle(strings.ToUpper("Get"),"/:uuid",h.VoucherForUUID)
    
}

