// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sob/{sobId}/account-classes": {
            "get": {
                "description": "List allowed account classes and their allowed groups",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.AccountClass"
                            }
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/account/{accountId}": {
            "get": {
                "description": "Get an account by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.AccountResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Account ID",
                        "name": "accountId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update account request",
                        "name": "UpdateAccountRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.UpdateAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/accounts": {
            "get": {
                "description": "List all accounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.AccountResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/auxiliaries": {
            "get": {
                "description": "List all auxiliary categories",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auxiliary accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "title eq 'something' and amount lt 10",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.AuxiliaryCategoryResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create auxiliary category",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auxiliary accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create auxiliary category request",
                        "name": "CreateAuxiliaryCategoryRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateAuxiliaryCategoryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/auxiliary/{categoryKey}/accounts": {
            "get": {
                "description": "List all auxiliary accounts",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auxiliary accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category Key",
                        "name": "categoryKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "title eq 'something' and amount lt 10",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.AuxiliaryAccountResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create auxiliary account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auxiliary accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Category Key",
                        "name": "categoryKey",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create auxiliary account request",
                        "name": "CreateAuxiliaryAccountRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateAuxiliaryAccountRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/first-period/ledgers": {
            "get": {
                "description": "List ledgers in first period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledgers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PeriodAndLedgersResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/ledgers/initialize": {
            "post": {
                "description": "Initialize ledgers in first period of current SoB",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledgers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Ledgers with opening balance",
                        "name": "InitializeLedgersBalanceRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.InitializeLedgersBalanceRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/period/{periodId}/auxiliary-ledgers": {
            "get": {
                "description": "List all auxiliary ledgers",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auxiliary ledgers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Period ID",
                        "name": "periodId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "title eq 'something' and amount lt 10",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.LedgerResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/period/{periodId}/close": {
            "post": {
                "description": "Close period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "periods"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Period ID",
                        "name": "periodId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/period/{periodId}/ledgers": {
            "get": {
                "description": "List ledgers in period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ledgers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Period ID",
                        "name": "periodId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "title eq 'something' and amount lt 10",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.LedgerResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/periods": {
            "get": {
                "description": "List periods",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "periods"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "title eq 'something' and amount lt 10",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.PeriodResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/periods/current": {
            "get": {
                "description": "Current period",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "periods"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.PeriodResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/search-accounts": {
            "get": {
                "description": "Search accounts with filters",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "accounts"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "title eq 'something' and amount lt 10",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.AccountResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/voucher/{voucherId}": {
            "get": {
                "description": "Show voucher by sob and id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.VoucherResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update voucher request",
                        "name": "UpdateVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.UpdateVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/voucher/{voucherId}/audit": {
            "post": {
                "description": "AuditVoucher voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "AuditVoucher voucher request, auditor user ID",
                        "name": "AuditVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AuditVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/voucher/{voucherId}/cancel-audit": {
            "post": {
                "description": "Cancel audit voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel audit voucher request, auditor user ID",
                        "name": "AuditVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AuditVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/voucher/{voucherId}/cancel-review": {
            "post": {
                "description": "Cancel review voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel review voucher request, reviewer user ID",
                        "name": "ReviewVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ReviewVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/voucher/{voucherId}/post": {
            "post": {
                "description": "PostVoucher voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "PostVoucher voucher request, poster user ID",
                        "name": "PostVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.PostVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/voucher/{voucherId}/review": {
            "post": {
                "description": "ReviewVoucher voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher ID",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ReviewVoucher voucher request, reviewer user ID",
                        "name": "ReviewVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ReviewVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sob/{sobId}/vouchers": {
            "get": {
                "description": "List all vouchers by sob with pagination",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "page number",
                        "name": "$page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 40,
                        "description": "page size",
                        "name": "$size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "updatedAt desc,createdAt",
                        "description": "sort on field(s)",
                        "name": "$sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "filter on field(s)",
                        "name": "$filter",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.VoucherResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create voucher request",
                        "name": "CreateVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.VoucherResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_general_ledger_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sobs": {
            "get": {
                "description": "List all sobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.SobResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create sob",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "parameters": [
                    {
                        "description": "CreateSob SobId",
                        "name": "CreateSobRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateSobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/http.SobResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sobs/{sobId}": {
            "get": {
                "description": "Show sob by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID of a SobId",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.SobResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update sob",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "SobId ID",
                        "name": "sobId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "UpdateLineItems sob request",
                        "name": "UpdateSobRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.UpdateSobRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/user/{userId}": {
            "get": {
                "description": "Show user by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Updater ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_user_port_public_http.UserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_user_port_public_http.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update user",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "Updater ID",
                        "name": "userId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user request",
                        "name": "UpdateUserRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.UpdateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_user_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_user_port_public_http.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.AccountClass": {
            "type": "object",
            "properties": {
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "http.AccountResponse": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "auxiliaryCategories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.AuxiliaryCategoryResponse"
                    }
                },
                "balanceDirection": {
                    "type": "string"
                },
                "class": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isLeaf": {
                    "type": "boolean"
                },
                "level": {
                    "type": "integer"
                },
                "numberHierarchy": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "sobId": {
                    "type": "string"
                },
                "superiorAccountId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.AuditVoucherRequest": {
            "type": "object",
            "properties": {
                "auditor": {
                    "type": "string"
                }
            }
        },
        "http.AuxiliaryAccountResponse": {
            "type": "object",
            "properties": {
                "category": {
                    "$ref": "#/definitions/http.AuxiliaryCategoryResponse"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.AuxiliaryCategoryResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isStandard": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "sobId": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.AuxiliaryItemRequest": {
            "type": "object",
            "properties": {
                "accountKey": {
                    "type": "string"
                },
                "categoryKey": {
                    "type": "string"
                }
            }
        },
        "http.CreateAuxiliaryAccountRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "http.CreateAuxiliaryCategoryRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "http.CreateSobRequest": {
            "type": "object",
            "properties": {
                "accountsCodeLength": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "baseCurrency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "startingPeriodMonth": {
                    "type": "integer"
                },
                "startingPeriodYear": {
                    "type": "integer"
                }
            }
        },
        "http.CreateVoucherRequest": {
            "type": "object",
            "properties": {
                "attachmentQuantity": {
                    "type": "integer"
                },
                "creator": {
                    "type": "string"
                },
                "headerText": {
                    "type": "string"
                },
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LineItemRequest"
                    }
                },
                "transactionTime": {
                    "type": "string"
                },
                "voucherType": {
                    "type": "string"
                }
            }
        },
        "http.InitializeLedgersBalanceItemRequest": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "openingBalance": {
                    "type": "number"
                }
            }
        },
        "http.InitializeLedgersBalanceRequest": {
            "type": "object",
            "required": [
                "ledgers"
            ],
            "properties": {
                "ledgers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.InitializeLedgersBalanceItemRequest"
                    }
                }
            }
        },
        "http.LedgerResponse": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/http.AccountResponse"
                },
                "accountId": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "endingCreditBalance": {
                    "type": "number"
                },
                "endingDebitBalance": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "openingCreditBalance": {
                    "type": "number"
                },
                "openingDebitBalance": {
                    "type": "number"
                },
                "periodCredit": {
                    "type": "number"
                },
                "periodDebit": {
                    "type": "number"
                },
                "periodId": {
                    "type": "string"
                },
                "sobId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.LineItemRequest": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "auxiliaryAccounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.AuxiliaryItemRequest"
                    }
                },
                "credit": {
                    "type": "number"
                },
                "debit": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "http.LineItemResponse": {
            "type": "object",
            "properties": {
                "account": {
                    "$ref": "#/definitions/http.AccountResponse"
                },
                "auxiliaryAccounts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.AuxiliaryAccountResponse"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "credit": {
                    "type": "number"
                },
                "debit": {
                    "type": "number"
                },
                "id": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.PeriodAndLedgersResponse": {
            "type": "object",
            "properties": {
                "ledgers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LedgerResponse"
                    }
                },
                "period": {
                    "$ref": "#/definitions/http.PeriodResponse"
                }
            }
        },
        "http.PeriodResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "endingTime": {
                    "type": "string"
                },
                "fiscalYear": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "isClosed": {
                    "type": "boolean"
                },
                "isCurrent": {
                    "type": "boolean"
                },
                "openingTime": {
                    "type": "string"
                },
                "periodNumber": {
                    "type": "integer"
                },
                "sobId": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "http.PostVoucherRequest": {
            "type": "object",
            "properties": {
                "poster": {
                    "type": "string"
                }
            }
        },
        "http.ReviewVoucherRequest": {
            "type": "object",
            "properties": {
                "reviewer": {
                    "type": "string"
                }
            }
        },
        "http.SobResponse": {
            "type": "object",
            "properties": {
                "accountsCodeLength": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "baseCurrency": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "startingPeriodMonth": {
                    "type": "integer"
                },
                "startingPeriodYear": {
                    "type": "integer"
                }
            }
        },
        "http.UpdateAccountRequest": {
            "type": "object",
            "properties": {
                "balanceDirection": {
                    "type": "string"
                },
                "categoryKeys": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "group": {
                    "type": "string"
                },
                "levelNumber": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "http.UpdateSobRequest": {
            "type": "object",
            "properties": {
                "accountsCodeLength": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "http.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "traits": {
                    "type": "string"
                }
            }
        },
        "http.UpdateVoucherRequest": {
            "type": "object",
            "properties": {
                "headerText": {
                    "type": "string"
                },
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LineItemRequest"
                    }
                },
                "transactionTime": {
                    "type": "string"
                },
                "updater": {
                    "type": "string"
                }
            }
        },
        "http.VoucherResponse": {
            "type": "object",
            "properties": {
                "attachmentQuantity": {
                    "type": "integer"
                },
                "auditor": {
                    "$ref": "#/definitions/internal_general_ledger_port_public_http.UserResponse"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "$ref": "#/definitions/internal_general_ledger_port_public_http.UserResponse"
                },
                "credit": {
                    "type": "number"
                },
                "debit": {
                    "type": "number"
                },
                "documentNumber": {
                    "type": "string"
                },
                "headerText": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isAudited": {
                    "type": "boolean"
                },
                "isPosted": {
                    "type": "boolean"
                },
                "isReviewed": {
                    "type": "boolean"
                },
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LineItemResponse"
                    }
                },
                "period": {
                    "$ref": "#/definitions/http.PeriodResponse"
                },
                "poster": {
                    "$ref": "#/definitions/internal_general_ledger_port_public_http.UserResponse"
                },
                "reviewer": {
                    "$ref": "#/definitions/internal_general_ledger_port_public_http.UserResponse"
                },
                "sobId": {
                    "type": "string"
                },
                "transactionTime": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "voucherType": {
                    "type": "string"
                }
            }
        },
        "internal_general_ledger_port_public_http.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_general_ledger_port_public_http.UserResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "traits": {}
            }
        },
        "internal_sob_port_public_http.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_user_port_public_http.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_user_port_public_http.UserResponse": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "traits": {},
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1",
	Host:             "127.0.0.1:4455",
	BasePath:         "/fims/api/v1",
	Schemes:          []string{},
	Title:            "FIMS prototype",
	Description:      "Prototype of FIMS",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
