// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sobs": {
            "get": {
                "description": "List all sobs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "summary": "List all sobs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.SobResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create sob",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "summary": "Create sob",
                "parameters": [
                    {
                        "description": "Create Sob",
                        "name": "sob",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.CreateSobRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/sobs/{sob}": {
            "get": {
                "description": "Show sob by id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sobs"
                ],
                "summary": "Show sob by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id of a Sob",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.SobResponse"
                        }
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_sob_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}": {
            "get": {
                "description": "List all vouchers by sob with paginagion",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "List all vouchers by sob",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/http.VoucherResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            },
            "post": {
                "description": "Create voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Create voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Create voucher request",
                        "name": "RecordVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.RecordVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}/{voucherId}": {
            "get": {
                "description": "Show voucher by sob and voucher id",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Show voucher by sob and voucher id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/http.VoucherResponse"
                        }
                    },
                    "404": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            },
            "patch": {
                "description": "Update voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Update voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update voucher request",
                        "name": "UpdateVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.UpdateVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}/{voucherId}/audit": {
            "post": {
                "description": "Audit voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Audit voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Audit voucher request, auditor user Id",
                        "name": "AuditVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AuditVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}/{voucherId}/cancel-audit": {
            "post": {
                "description": "Cancel audit voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Cancel audit voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel audit voucher request, , auditor user Id",
                        "name": "AuditVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.AuditVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}/{voucherId}/cancel-review": {
            "post": {
                "description": "Cancel review voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Cancel review voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Cancel review voucher request, reviewer user Id",
                        "name": "ReviewVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ReviewVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}/{voucherId}/post": {
            "post": {
                "description": "Post voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Post voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        },
        "/vouchers/{sob}/{voucherId}/review": {
            "post": {
                "description": "Review voucher",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vouchers"
                ],
                "summary": "Review voucher",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Sob Id",
                        "name": "sob",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Voucher Id",
                        "name": "voucherId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Review voucher request, reviewer user Id",
                        "name": "ReviewVoucherRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/http.ReviewVoucherRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": ""
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_voucher_port_public_http.Error"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.AuditVoucherRequest": {
            "type": "object",
            "properties": {
                "auditor": {
                    "type": "string"
                }
            }
        },
        "http.CreateSobRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "http.LineItemRequest": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "credit": {
                    "type": "string"
                },
                "debit": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "http.LineItemResponse": {
            "type": "object",
            "properties": {
                "accountNumber": {
                    "type": "string"
                },
                "credit": {
                    "type": "string"
                },
                "debit": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "summary": {
                    "type": "string"
                }
            }
        },
        "http.RecordVoucherRequest": {
            "type": "object",
            "properties": {
                "attachmentQuantity": {
                    "type": "integer"
                },
                "creator": {
                    "type": "string"
                },
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LineItemRequest"
                    }
                },
                "voucherType": {
                    "type": "string"
                }
            }
        },
        "http.ReviewVoucherRequest": {
            "type": "object",
            "properties": {
                "reviewer": {
                    "type": "string"
                }
            }
        },
        "http.SobResponse": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "http.UpdateVoucherRequest": {
            "type": "object",
            "properties": {
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LineItemRequest"
                    }
                }
            }
        },
        "http.VoucherResponse": {
            "type": "object",
            "properties": {
                "attachmentQuantity": {
                    "type": "integer"
                },
                "auditor": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "creator": {
                    "type": "string"
                },
                "credit": {
                    "type": "string"
                },
                "debit": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isAudited": {
                    "type": "boolean"
                },
                "isPosted": {
                    "type": "boolean"
                },
                "isReviewed": {
                    "type": "boolean"
                },
                "lineItems": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/http.LineItemResponse"
                    }
                },
                "number": {
                    "type": "string"
                },
                "reviewer": {
                    "type": "string"
                },
                "sob": {
                    "type": "string"
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "internal_sob_port_public_http.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        },
        "internal_voucher_port_public_http.Error": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "0.1",
	Host:        "localhost:3000",
	BasePath:    "/api/v1",
	Schemes:     []string{},
	Title:       "FIMS prototype",
	Description: "Prototype of FIMS",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register("swagger", &s{})
}
