package filterable

// Code generated by peg -output internal/common/data/filterable/filterable_ast.go internal/common/data/filterable/filterable.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleF
	ruleExprList
	ruleExpr
	ruleAtomExpr
	ruleNotExpr
	ruleAndExpr
	ruleOrExpr
	ruleEqExpr
	ruleNeExpr
	ruleLtExpr
	ruleGtExpr
	ruleLteExpr
	ruleGteExpr
	ruleStwExpr
	ruleBtwExpr
	ruleCtnExpr
	ruleIdentifier
	ruleIdentStart
	ruleIdentCont
	ruleLiteral
	ruleStringLiteral
	ruleEscape
	ruleOctalEscape
	ruleUnicodeEscape
	ruleNumLiteral
	ruleDigits
	ruleHexDigit
	ruleNOT
	ruleAND
	ruleOR
	ruleEQ
	ruleNE
	ruleLT
	ruleGT
	ruleLTE
	ruleGTE
	ruleBTW
	ruleSTW
	ruleCTN
	ruleLPAR
	ruleRPAR
	ruleCOMMA
	ruleSpacing
	ruleEOT
	rulePegText
)

var rul3s = [...]string{
	"Unknown",
	"F",
	"ExprList",
	"Expr",
	"AtomExpr",
	"NotExpr",
	"AndExpr",
	"OrExpr",
	"EqExpr",
	"NeExpr",
	"LtExpr",
	"GtExpr",
	"LteExpr",
	"GteExpr",
	"StwExpr",
	"BtwExpr",
	"CtnExpr",
	"Identifier",
	"IdentStart",
	"IdentCont",
	"Literal",
	"StringLiteral",
	"Escape",
	"OctalEscape",
	"UnicodeEscape",
	"NumLiteral",
	"Digits",
	"HexDigit",
	"NOT",
	"AND",
	"OR",
	"EQ",
	"NE",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"BTW",
	"STW",
	"CTN",
	"LPAR",
	"RPAR",
	"COMMA",
	"Spacing",
	"EOT",
	"PegText",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type FilterExpr struct {
	Buffer string
	buffer []rune
	rules  [46]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *FilterExpr) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *FilterExpr) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *FilterExpr
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *FilterExpr) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *FilterExpr) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *FilterExpr) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*FilterExpr) error {
	return func(p *FilterExpr) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*FilterExpr) error {
	return func(p *FilterExpr) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *FilterExpr) Init(options ...func(*FilterExpr) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 F <- <(Spacing Expr EOT)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[ruleSpacing]() {
					goto l0
				}
				if !_rules[ruleExpr]() {
					goto l0
				}
				if !_rules[ruleEOT]() {
					goto l0
				}
				add(ruleF, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 ExprList <- <(Expr (COMMA Spacing Expr)+)> */
		func() bool {
			position2, tokenIndex2 := position, tokenIndex
			{
				position3 := position
				if !_rules[ruleExpr]() {
					goto l2
				}
				if !_rules[ruleCOMMA]() {
					goto l2
				}
				if !_rules[ruleSpacing]() {
					goto l2
				}
				if !_rules[ruleExpr]() {
					goto l2
				}
			l4:
				{
					position5, tokenIndex5 := position, tokenIndex
					if !_rules[ruleCOMMA]() {
						goto l5
					}
					if !_rules[ruleSpacing]() {
						goto l5
					}
					if !_rules[ruleExpr]() {
						goto l5
					}
					goto l4
				l5:
					position, tokenIndex = position5, tokenIndex5
				}
				add(ruleExprList, position3)
			}
			return true
		l2:
			position, tokenIndex = position2, tokenIndex2
			return false
		},
		/* 2 Expr <- <((NotExpr / AndExpr / OrExpr / AtomExpr) Spacing)> */
		func() bool {
			position6, tokenIndex6 := position, tokenIndex
			{
				position7 := position
				{
					position8, tokenIndex8 := position, tokenIndex
					if !_rules[ruleNotExpr]() {
						goto l9
					}
					goto l8
				l9:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleAndExpr]() {
						goto l10
					}
					goto l8
				l10:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleOrExpr]() {
						goto l11
					}
					goto l8
				l11:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleAtomExpr]() {
						goto l6
					}
				}
			l8:
				if !_rules[ruleSpacing]() {
					goto l6
				}
				add(ruleExpr, position7)
			}
			return true
		l6:
			position, tokenIndex = position6, tokenIndex6
			return false
		},
		/* 3 AtomExpr <- <((EqExpr / NeExpr / LtExpr / GtExpr / LteExpr / GteExpr / StwExpr / BtwExpr / CtnExpr / ) Spacing)> */
		func() bool {
			position12, tokenIndex12 := position, tokenIndex
			{
				position13 := position
				{
					position14, tokenIndex14 := position, tokenIndex
					if !_rules[ruleEqExpr]() {
						goto l15
					}
					goto l14
				l15:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleNeExpr]() {
						goto l16
					}
					goto l14
				l16:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleLtExpr]() {
						goto l17
					}
					goto l14
				l17:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleGtExpr]() {
						goto l18
					}
					goto l14
				l18:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleLteExpr]() {
						goto l19
					}
					goto l14
				l19:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleGteExpr]() {
						goto l20
					}
					goto l14
				l20:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleStwExpr]() {
						goto l21
					}
					goto l14
				l21:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleBtwExpr]() {
						goto l22
					}
					goto l14
				l22:
					position, tokenIndex = position14, tokenIndex14
					if !_rules[ruleCtnExpr]() {
						goto l23
					}
					goto l14
				l23:
					position, tokenIndex = position14, tokenIndex14
				}
			l14:
				if !_rules[ruleSpacing]() {
					goto l12
				}
				add(ruleAtomExpr, position13)
			}
			return true
		l12:
			position, tokenIndex = position12, tokenIndex12
			return false
		},
		/* 4 NotExpr <- <(NOT LPAR Expr RPAR)> */
		func() bool {
			position24, tokenIndex24 := position, tokenIndex
			{
				position25 := position
				if !_rules[ruleNOT]() {
					goto l24
				}
				if !_rules[ruleLPAR]() {
					goto l24
				}
				if !_rules[ruleExpr]() {
					goto l24
				}
				if !_rules[ruleRPAR]() {
					goto l24
				}
				add(ruleNotExpr, position25)
			}
			return true
		l24:
			position, tokenIndex = position24, tokenIndex24
			return false
		},
		/* 5 AndExpr <- <(AND LPAR ExprList RPAR)> */
		func() bool {
			position26, tokenIndex26 := position, tokenIndex
			{
				position27 := position
				if !_rules[ruleAND]() {
					goto l26
				}
				if !_rules[ruleLPAR]() {
					goto l26
				}
				if !_rules[ruleExprList]() {
					goto l26
				}
				if !_rules[ruleRPAR]() {
					goto l26
				}
				add(ruleAndExpr, position27)
			}
			return true
		l26:
			position, tokenIndex = position26, tokenIndex26
			return false
		},
		/* 6 OrExpr <- <(OR LPAR ExprList RPAR)> */
		func() bool {
			position28, tokenIndex28 := position, tokenIndex
			{
				position29 := position
				if !_rules[ruleOR]() {
					goto l28
				}
				if !_rules[ruleLPAR]() {
					goto l28
				}
				if !_rules[ruleExprList]() {
					goto l28
				}
				if !_rules[ruleRPAR]() {
					goto l28
				}
				add(ruleOrExpr, position29)
			}
			return true
		l28:
			position, tokenIndex = position28, tokenIndex28
			return false
		},
		/* 7 EqExpr <- <(EQ LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position30, tokenIndex30 := position, tokenIndex
			{
				position31 := position
				if !_rules[ruleEQ]() {
					goto l30
				}
				if !_rules[ruleLPAR]() {
					goto l30
				}
				if !_rules[ruleIdentifier]() {
					goto l30
				}
				if !_rules[ruleCOMMA]() {
					goto l30
				}
				if !_rules[ruleLiteral]() {
					goto l30
				}
				if !_rules[ruleRPAR]() {
					goto l30
				}
				add(ruleEqExpr, position31)
			}
			return true
		l30:
			position, tokenIndex = position30, tokenIndex30
			return false
		},
		/* 8 NeExpr <- <(NE LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position32, tokenIndex32 := position, tokenIndex
			{
				position33 := position
				if !_rules[ruleNE]() {
					goto l32
				}
				if !_rules[ruleLPAR]() {
					goto l32
				}
				if !_rules[ruleIdentifier]() {
					goto l32
				}
				if !_rules[ruleCOMMA]() {
					goto l32
				}
				if !_rules[ruleLiteral]() {
					goto l32
				}
				if !_rules[ruleRPAR]() {
					goto l32
				}
				add(ruleNeExpr, position33)
			}
			return true
		l32:
			position, tokenIndex = position32, tokenIndex32
			return false
		},
		/* 9 LtExpr <- <(LT LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position34, tokenIndex34 := position, tokenIndex
			{
				position35 := position
				if !_rules[ruleLT]() {
					goto l34
				}
				if !_rules[ruleLPAR]() {
					goto l34
				}
				if !_rules[ruleIdentifier]() {
					goto l34
				}
				if !_rules[ruleCOMMA]() {
					goto l34
				}
				if !_rules[ruleLiteral]() {
					goto l34
				}
				if !_rules[ruleRPAR]() {
					goto l34
				}
				add(ruleLtExpr, position35)
			}
			return true
		l34:
			position, tokenIndex = position34, tokenIndex34
			return false
		},
		/* 10 GtExpr <- <(GT LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position36, tokenIndex36 := position, tokenIndex
			{
				position37 := position
				if !_rules[ruleGT]() {
					goto l36
				}
				if !_rules[ruleLPAR]() {
					goto l36
				}
				if !_rules[ruleIdentifier]() {
					goto l36
				}
				if !_rules[ruleCOMMA]() {
					goto l36
				}
				if !_rules[ruleLiteral]() {
					goto l36
				}
				if !_rules[ruleRPAR]() {
					goto l36
				}
				add(ruleGtExpr, position37)
			}
			return true
		l36:
			position, tokenIndex = position36, tokenIndex36
			return false
		},
		/* 11 LteExpr <- <(LTE LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position38, tokenIndex38 := position, tokenIndex
			{
				position39 := position
				if !_rules[ruleLTE]() {
					goto l38
				}
				if !_rules[ruleLPAR]() {
					goto l38
				}
				if !_rules[ruleIdentifier]() {
					goto l38
				}
				if !_rules[ruleCOMMA]() {
					goto l38
				}
				if !_rules[ruleLiteral]() {
					goto l38
				}
				if !_rules[ruleRPAR]() {
					goto l38
				}
				add(ruleLteExpr, position39)
			}
			return true
		l38:
			position, tokenIndex = position38, tokenIndex38
			return false
		},
		/* 12 GteExpr <- <(GTE LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position40, tokenIndex40 := position, tokenIndex
			{
				position41 := position
				if !_rules[ruleGTE]() {
					goto l40
				}
				if !_rules[ruleLPAR]() {
					goto l40
				}
				if !_rules[ruleIdentifier]() {
					goto l40
				}
				if !_rules[ruleCOMMA]() {
					goto l40
				}
				if !_rules[ruleLiteral]() {
					goto l40
				}
				if !_rules[ruleRPAR]() {
					goto l40
				}
				add(ruleGteExpr, position41)
			}
			return true
		l40:
			position, tokenIndex = position40, tokenIndex40
			return false
		},
		/* 13 StwExpr <- <(STW LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position42, tokenIndex42 := position, tokenIndex
			{
				position43 := position
				if !_rules[ruleSTW]() {
					goto l42
				}
				if !_rules[ruleLPAR]() {
					goto l42
				}
				if !_rules[ruleIdentifier]() {
					goto l42
				}
				if !_rules[ruleCOMMA]() {
					goto l42
				}
				if !_rules[ruleLiteral]() {
					goto l42
				}
				if !_rules[ruleRPAR]() {
					goto l42
				}
				add(ruleStwExpr, position43)
			}
			return true
		l42:
			position, tokenIndex = position42, tokenIndex42
			return false
		},
		/* 14 BtwExpr <- <(BTW LPAR Identifier COMMA Literal COMMA Literal RPAR)> */
		func() bool {
			position44, tokenIndex44 := position, tokenIndex
			{
				position45 := position
				if !_rules[ruleBTW]() {
					goto l44
				}
				if !_rules[ruleLPAR]() {
					goto l44
				}
				if !_rules[ruleIdentifier]() {
					goto l44
				}
				if !_rules[ruleCOMMA]() {
					goto l44
				}
				if !_rules[ruleLiteral]() {
					goto l44
				}
				if !_rules[ruleCOMMA]() {
					goto l44
				}
				if !_rules[ruleLiteral]() {
					goto l44
				}
				if !_rules[ruleRPAR]() {
					goto l44
				}
				add(ruleBtwExpr, position45)
			}
			return true
		l44:
			position, tokenIndex = position44, tokenIndex44
			return false
		},
		/* 15 CtnExpr <- <(CTN LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position46, tokenIndex46 := position, tokenIndex
			{
				position47 := position
				if !_rules[ruleCTN]() {
					goto l46
				}
				if !_rules[ruleLPAR]() {
					goto l46
				}
				if !_rules[ruleIdentifier]() {
					goto l46
				}
				if !_rules[ruleCOMMA]() {
					goto l46
				}
				if !_rules[ruleLiteral]() {
					goto l46
				}
				if !_rules[ruleRPAR]() {
					goto l46
				}
				add(ruleCtnExpr, position47)
			}
			return true
		l46:
			position, tokenIndex = position46, tokenIndex46
			return false
		},
		/* 16 Identifier <- <(<(IdentStart IdentCont*)> Spacing)> */
		func() bool {
			position48, tokenIndex48 := position, tokenIndex
			{
				position49 := position
				{
					position50 := position
					if !_rules[ruleIdentStart]() {
						goto l48
					}
				l51:
					{
						position52, tokenIndex52 := position, tokenIndex
						if !_rules[ruleIdentCont]() {
							goto l52
						}
						goto l51
					l52:
						position, tokenIndex = position52, tokenIndex52
					}
					add(rulePegText, position50)
				}
				if !_rules[ruleSpacing]() {
					goto l48
				}
				add(ruleIdentifier, position49)
			}
			return true
		l48:
			position, tokenIndex = position48, tokenIndex48
			return false
		},
		/* 17 IdentStart <- <([a-z] / [A-Z] / '_')> */
		func() bool {
			position53, tokenIndex53 := position, tokenIndex
			{
				position54 := position
				{
					position55, tokenIndex55 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l56
					}
					position++
					goto l55
				l56:
					position, tokenIndex = position55, tokenIndex55
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l57
					}
					position++
					goto l55
				l57:
					position, tokenIndex = position55, tokenIndex55
					if buffer[position] != rune('_') {
						goto l53
					}
					position++
				}
			l55:
				add(ruleIdentStart, position54)
			}
			return true
		l53:
			position, tokenIndex = position53, tokenIndex53
			return false
		},
		/* 18 IdentCont <- <(IdentStart / [0-9])> */
		func() bool {
			position58, tokenIndex58 := position, tokenIndex
			{
				position59 := position
				{
					position60, tokenIndex60 := position, tokenIndex
					if !_rules[ruleIdentStart]() {
						goto l61
					}
					goto l60
				l61:
					position, tokenIndex = position60, tokenIndex60
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l58
					}
					position++
				}
			l60:
				add(ruleIdentCont, position59)
			}
			return true
		l58:
			position, tokenIndex = position58, tokenIndex58
			return false
		},
		/* 19 Literal <- <(StringLiteral / NumLiteral)> */
		func() bool {
			position62, tokenIndex62 := position, tokenIndex
			{
				position63 := position
				{
					position64, tokenIndex64 := position, tokenIndex
					if !_rules[ruleStringLiteral]() {
						goto l65
					}
					goto l64
				l65:
					position, tokenIndex = position64, tokenIndex64
					if !_rules[ruleNumLiteral]() {
						goto l62
					}
				}
			l64:
				add(ruleLiteral, position63)
			}
			return true
		l62:
			position, tokenIndex = position62, tokenIndex62
			return false
		},
		/* 20 StringLiteral <- <('"' (Escape / (!('"' / '\\' / '\n' / '\r') .))* '"')> */
		func() bool {
			position66, tokenIndex66 := position, tokenIndex
			{
				position67 := position
				if buffer[position] != rune('"') {
					goto l66
				}
				position++
			l68:
				{
					position69, tokenIndex69 := position, tokenIndex
					{
						position70, tokenIndex70 := position, tokenIndex
						if !_rules[ruleEscape]() {
							goto l71
						}
						goto l70
					l71:
						position, tokenIndex = position70, tokenIndex70
						{
							position72, tokenIndex72 := position, tokenIndex
							{
								position73, tokenIndex73 := position, tokenIndex
								if buffer[position] != rune('"') {
									goto l74
								}
								position++
								goto l73
							l74:
								position, tokenIndex = position73, tokenIndex73
								if buffer[position] != rune('\\') {
									goto l75
								}
								position++
								goto l73
							l75:
								position, tokenIndex = position73, tokenIndex73
								if buffer[position] != rune('\n') {
									goto l76
								}
								position++
								goto l73
							l76:
								position, tokenIndex = position73, tokenIndex73
								if buffer[position] != rune('\r') {
									goto l72
								}
								position++
							}
						l73:
							goto l69
						l72:
							position, tokenIndex = position72, tokenIndex72
						}
						if !matchDot() {
							goto l69
						}
					}
				l70:
					goto l68
				l69:
					position, tokenIndex = position69, tokenIndex69
				}
				if buffer[position] != rune('"') {
					goto l66
				}
				position++
				add(ruleStringLiteral, position67)
			}
			return true
		l66:
			position, tokenIndex = position66, tokenIndex66
			return false
		},
		/* 21 Escape <- <('\\' ('b' / 't' / 'n' / 'f' / 'r' / '"' / '\'' / '\\' / OctalEscape / UnicodeEscape))> */
		func() bool {
			position77, tokenIndex77 := position, tokenIndex
			{
				position78 := position
				if buffer[position] != rune('\\') {
					goto l77
				}
				position++
				{
					position79, tokenIndex79 := position, tokenIndex
					if buffer[position] != rune('b') {
						goto l80
					}
					position++
					goto l79
				l80:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('t') {
						goto l81
					}
					position++
					goto l79
				l81:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('n') {
						goto l82
					}
					position++
					goto l79
				l82:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('f') {
						goto l83
					}
					position++
					goto l79
				l83:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('r') {
						goto l84
					}
					position++
					goto l79
				l84:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('"') {
						goto l85
					}
					position++
					goto l79
				l85:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('\'') {
						goto l86
					}
					position++
					goto l79
				l86:
					position, tokenIndex = position79, tokenIndex79
					if buffer[position] != rune('\\') {
						goto l87
					}
					position++
					goto l79
				l87:
					position, tokenIndex = position79, tokenIndex79
					if !_rules[ruleOctalEscape]() {
						goto l88
					}
					goto l79
				l88:
					position, tokenIndex = position79, tokenIndex79
					if !_rules[ruleUnicodeEscape]() {
						goto l77
					}
				}
			l79:
				add(ruleEscape, position78)
			}
			return true
		l77:
			position, tokenIndex = position77, tokenIndex77
			return false
		},
		/* 22 OctalEscape <- <(([0-3] [0-7] [0-7]) / ([0-7] [0-7]) / [0-7])> */
		func() bool {
			position89, tokenIndex89 := position, tokenIndex
			{
				position90 := position
				{
					position91, tokenIndex91 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('3') {
						goto l92
					}
					position++
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l92
					}
					position++
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l92
					}
					position++
					goto l91
				l92:
					position, tokenIndex = position91, tokenIndex91
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l93
					}
					position++
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l93
					}
					position++
					goto l91
				l93:
					position, tokenIndex = position91, tokenIndex91
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l89
					}
					position++
				}
			l91:
				add(ruleOctalEscape, position90)
			}
			return true
		l89:
			position, tokenIndex = position89, tokenIndex89
			return false
		},
		/* 23 UnicodeEscape <- <('u'+ HexDigit HexDigit HexDigit HexDigit)> */
		func() bool {
			position94, tokenIndex94 := position, tokenIndex
			{
				position95 := position
				if buffer[position] != rune('u') {
					goto l94
				}
				position++
			l96:
				{
					position97, tokenIndex97 := position, tokenIndex
					if buffer[position] != rune('u') {
						goto l97
					}
					position++
					goto l96
				l97:
					position, tokenIndex = position97, tokenIndex97
				}
				if !_rules[ruleHexDigit]() {
					goto l94
				}
				if !_rules[ruleHexDigit]() {
					goto l94
				}
				if !_rules[ruleHexDigit]() {
					goto l94
				}
				if !_rules[ruleHexDigit]() {
					goto l94
				}
				add(ruleUnicodeEscape, position95)
			}
			return true
		l94:
			position, tokenIndex = position94, tokenIndex94
			return false
		},
		/* 24 NumLiteral <- <((Digits '.' Digits?) / Digits)> */
		func() bool {
			position98, tokenIndex98 := position, tokenIndex
			{
				position99 := position
				{
					position100, tokenIndex100 := position, tokenIndex
					if !_rules[ruleDigits]() {
						goto l101
					}
					if buffer[position] != rune('.') {
						goto l101
					}
					position++
					{
						position102, tokenIndex102 := position, tokenIndex
						if !_rules[ruleDigits]() {
							goto l102
						}
						goto l103
					l102:
						position, tokenIndex = position102, tokenIndex102
					}
				l103:
					goto l100
				l101:
					position, tokenIndex = position100, tokenIndex100
					if !_rules[ruleDigits]() {
						goto l98
					}
				}
			l100:
				add(ruleNumLiteral, position99)
			}
			return true
		l98:
			position, tokenIndex = position98, tokenIndex98
			return false
		},
		/* 25 Digits <- <([0-9] ('_'* [0-9])*)> */
		func() bool {
			position104, tokenIndex104 := position, tokenIndex
			{
				position105 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l104
				}
				position++
			l106:
				{
					position107, tokenIndex107 := position, tokenIndex
				l108:
					{
						position109, tokenIndex109 := position, tokenIndex
						if buffer[position] != rune('_') {
							goto l109
						}
						position++
						goto l108
					l109:
						position, tokenIndex = position109, tokenIndex109
					}
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l107
					}
					position++
					goto l106
				l107:
					position, tokenIndex = position107, tokenIndex107
				}
				add(ruleDigits, position105)
			}
			return true
		l104:
			position, tokenIndex = position104, tokenIndex104
			return false
		},
		/* 26 HexDigit <- <([a-f] / [A-F] / [0-9])> */
		func() bool {
			position110, tokenIndex110 := position, tokenIndex
			{
				position111 := position
				{
					position112, tokenIndex112 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('f') {
						goto l113
					}
					position++
					goto l112
				l113:
					position, tokenIndex = position112, tokenIndex112
					if c := buffer[position]; c < rune('A') || c > rune('F') {
						goto l114
					}
					position++
					goto l112
				l114:
					position, tokenIndex = position112, tokenIndex112
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l110
					}
					position++
				}
			l112:
				add(ruleHexDigit, position111)
			}
			return true
		l110:
			position, tokenIndex = position110, tokenIndex110
			return false
		},
		/* 27 NOT <- <('n' 'o' 't' Spacing)> */
		func() bool {
			position115, tokenIndex115 := position, tokenIndex
			{
				position116 := position
				if buffer[position] != rune('n') {
					goto l115
				}
				position++
				if buffer[position] != rune('o') {
					goto l115
				}
				position++
				if buffer[position] != rune('t') {
					goto l115
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l115
				}
				add(ruleNOT, position116)
			}
			return true
		l115:
			position, tokenIndex = position115, tokenIndex115
			return false
		},
		/* 28 AND <- <('a' 'n' 'd' Spacing)> */
		func() bool {
			position117, tokenIndex117 := position, tokenIndex
			{
				position118 := position
				if buffer[position] != rune('a') {
					goto l117
				}
				position++
				if buffer[position] != rune('n') {
					goto l117
				}
				position++
				if buffer[position] != rune('d') {
					goto l117
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l117
				}
				add(ruleAND, position118)
			}
			return true
		l117:
			position, tokenIndex = position117, tokenIndex117
			return false
		},
		/* 29 OR <- <('o' 'r' Spacing)> */
		func() bool {
			position119, tokenIndex119 := position, tokenIndex
			{
				position120 := position
				if buffer[position] != rune('o') {
					goto l119
				}
				position++
				if buffer[position] != rune('r') {
					goto l119
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l119
				}
				add(ruleOR, position120)
			}
			return true
		l119:
			position, tokenIndex = position119, tokenIndex119
			return false
		},
		/* 30 EQ <- <('e' 'q' Spacing)> */
		func() bool {
			position121, tokenIndex121 := position, tokenIndex
			{
				position122 := position
				if buffer[position] != rune('e') {
					goto l121
				}
				position++
				if buffer[position] != rune('q') {
					goto l121
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l121
				}
				add(ruleEQ, position122)
			}
			return true
		l121:
			position, tokenIndex = position121, tokenIndex121
			return false
		},
		/* 31 NE <- <('n' 'e' Spacing)> */
		func() bool {
			position123, tokenIndex123 := position, tokenIndex
			{
				position124 := position
				if buffer[position] != rune('n') {
					goto l123
				}
				position++
				if buffer[position] != rune('e') {
					goto l123
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l123
				}
				add(ruleNE, position124)
			}
			return true
		l123:
			position, tokenIndex = position123, tokenIndex123
			return false
		},
		/* 32 LT <- <('l' 't' Spacing)> */
		func() bool {
			position125, tokenIndex125 := position, tokenIndex
			{
				position126 := position
				if buffer[position] != rune('l') {
					goto l125
				}
				position++
				if buffer[position] != rune('t') {
					goto l125
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l125
				}
				add(ruleLT, position126)
			}
			return true
		l125:
			position, tokenIndex = position125, tokenIndex125
			return false
		},
		/* 33 GT <- <('g' 't' Spacing)> */
		func() bool {
			position127, tokenIndex127 := position, tokenIndex
			{
				position128 := position
				if buffer[position] != rune('g') {
					goto l127
				}
				position++
				if buffer[position] != rune('t') {
					goto l127
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l127
				}
				add(ruleGT, position128)
			}
			return true
		l127:
			position, tokenIndex = position127, tokenIndex127
			return false
		},
		/* 34 LTE <- <('l' 't' 'e' Spacing)> */
		func() bool {
			position129, tokenIndex129 := position, tokenIndex
			{
				position130 := position
				if buffer[position] != rune('l') {
					goto l129
				}
				position++
				if buffer[position] != rune('t') {
					goto l129
				}
				position++
				if buffer[position] != rune('e') {
					goto l129
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l129
				}
				add(ruleLTE, position130)
			}
			return true
		l129:
			position, tokenIndex = position129, tokenIndex129
			return false
		},
		/* 35 GTE <- <('g' 't' 'e' Spacing)> */
		func() bool {
			position131, tokenIndex131 := position, tokenIndex
			{
				position132 := position
				if buffer[position] != rune('g') {
					goto l131
				}
				position++
				if buffer[position] != rune('t') {
					goto l131
				}
				position++
				if buffer[position] != rune('e') {
					goto l131
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l131
				}
				add(ruleGTE, position132)
			}
			return true
		l131:
			position, tokenIndex = position131, tokenIndex131
			return false
		},
		/* 36 BTW <- <('b' 't' 'w' Spacing)> */
		func() bool {
			position133, tokenIndex133 := position, tokenIndex
			{
				position134 := position
				if buffer[position] != rune('b') {
					goto l133
				}
				position++
				if buffer[position] != rune('t') {
					goto l133
				}
				position++
				if buffer[position] != rune('w') {
					goto l133
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l133
				}
				add(ruleBTW, position134)
			}
			return true
		l133:
			position, tokenIndex = position133, tokenIndex133
			return false
		},
		/* 37 STW <- <('s' 't' 'w' Spacing)> */
		func() bool {
			position135, tokenIndex135 := position, tokenIndex
			{
				position136 := position
				if buffer[position] != rune('s') {
					goto l135
				}
				position++
				if buffer[position] != rune('t') {
					goto l135
				}
				position++
				if buffer[position] != rune('w') {
					goto l135
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l135
				}
				add(ruleSTW, position136)
			}
			return true
		l135:
			position, tokenIndex = position135, tokenIndex135
			return false
		},
		/* 38 CTN <- <('c' 't' 'n' Spacing)> */
		func() bool {
			position137, tokenIndex137 := position, tokenIndex
			{
				position138 := position
				if buffer[position] != rune('c') {
					goto l137
				}
				position++
				if buffer[position] != rune('t') {
					goto l137
				}
				position++
				if buffer[position] != rune('n') {
					goto l137
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l137
				}
				add(ruleCTN, position138)
			}
			return true
		l137:
			position, tokenIndex = position137, tokenIndex137
			return false
		},
		/* 39 LPAR <- <('(' Spacing)> */
		func() bool {
			position139, tokenIndex139 := position, tokenIndex
			{
				position140 := position
				if buffer[position] != rune('(') {
					goto l139
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l139
				}
				add(ruleLPAR, position140)
			}
			return true
		l139:
			position, tokenIndex = position139, tokenIndex139
			return false
		},
		/* 40 RPAR <- <(')' Spacing)> */
		func() bool {
			position141, tokenIndex141 := position, tokenIndex
			{
				position142 := position
				if buffer[position] != rune(')') {
					goto l141
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l141
				}
				add(ruleRPAR, position142)
			}
			return true
		l141:
			position, tokenIndex = position141, tokenIndex141
			return false
		},
		/* 41 COMMA <- <(',' Spacing)> */
		func() bool {
			position143, tokenIndex143 := position, tokenIndex
			{
				position144 := position
				if buffer[position] != rune(',') {
					goto l143
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l143
				}
				add(ruleCOMMA, position144)
			}
			return true
		l143:
			position, tokenIndex = position143, tokenIndex143
			return false
		},
		/* 42 Spacing <- <(' ' / '\t')*> */
		func() bool {
			{
				position146 := position
			l147:
				{
					position148, tokenIndex148 := position, tokenIndex
					{
						position149, tokenIndex149 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l150
						}
						position++
						goto l149
					l150:
						position, tokenIndex = position149, tokenIndex149
						if buffer[position] != rune('\t') {
							goto l148
						}
						position++
					}
				l149:
					goto l147
				l148:
					position, tokenIndex = position148, tokenIndex148
				}
				add(ruleSpacing, position146)
			}
			return true
		},
		/* 43 EOT <- <!.> */
		func() bool {
			position151, tokenIndex151 := position, tokenIndex
			{
				position152 := position
				{
					position153, tokenIndex153 := position, tokenIndex
					if !matchDot() {
						goto l153
					}
					goto l151
				l153:
					position, tokenIndex = position153, tokenIndex153
				}
				add(ruleEOT, position152)
			}
			return true
		l151:
			position, tokenIndex = position151, tokenIndex151
			return false
		},
		nil,
	}
	p.rules = _rules
	return nil
}
