package filterable

// Code generated by peg -output internal/common/data/filterable/filterable_ast.go internal/common/data/filterable/filterable.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleF
	ruleExprList
	ruleExpr
	ruleNotExpr
	ruleAndExpr
	ruleOrExpr
	ruleEqExpr
	ruleNeExpr
	ruleLtExpr
	ruleGtExpr
	ruleLteExpr
	ruleGteExpr
	ruleStwExpr
	ruleBtwExpr
	ruleCtnExpr
	ruleIdentifier
	ruleIdentStart
	ruleIdentCont
	ruleLiteral
	ruleStringLiteral
	ruleEscape
	ruleOctalEscape
	ruleUnicodeEscape
	ruleNumLiteral
	ruleDigits
	ruleHexDigit
	ruleNOT
	ruleAND
	ruleOR
	ruleEQ
	ruleNE
	ruleLT
	ruleGT
	ruleLTE
	ruleGTE
	ruleBTW
	ruleSTW
	ruleCTN
	ruleLPAR
	ruleRPAR
	ruleCOMMA
	ruleSpacing
	ruleEOT
	rulePegText
)

var rul3s = [...]string{
	"Unknown",
	"F",
	"ExprList",
	"Expr",
	"NotExpr",
	"AndExpr",
	"OrExpr",
	"EqExpr",
	"NeExpr",
	"LtExpr",
	"GtExpr",
	"LteExpr",
	"GteExpr",
	"StwExpr",
	"BtwExpr",
	"CtnExpr",
	"Identifier",
	"IdentStart",
	"IdentCont",
	"Literal",
	"StringLiteral",
	"Escape",
	"OctalEscape",
	"UnicodeEscape",
	"NumLiteral",
	"Digits",
	"HexDigit",
	"NOT",
	"AND",
	"OR",
	"EQ",
	"NE",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"BTW",
	"STW",
	"CTN",
	"LPAR",
	"RPAR",
	"COMMA",
	"Spacing",
	"EOT",
	"PegText",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type FilterExpr struct {
	Buffer string
	buffer []rune
	rules  [45]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *FilterExpr) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *FilterExpr) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *FilterExpr
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *FilterExpr) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *FilterExpr) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *FilterExpr) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*FilterExpr) error {
	return func(p *FilterExpr) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*FilterExpr) error {
	return func(p *FilterExpr) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *FilterExpr) Init(options ...func(*FilterExpr) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 F <- <(Spacing Expr EOT)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[ruleSpacing]() {
					goto l0
				}
				if !_rules[ruleExpr]() {
					goto l0
				}
				if !_rules[ruleEOT]() {
					goto l0
				}
				add(ruleF, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 ExprList <- <(Expr (COMMA Spacing Expr)+)> */
		func() bool {
			position2, tokenIndex2 := position, tokenIndex
			{
				position3 := position
				if !_rules[ruleExpr]() {
					goto l2
				}
				if !_rules[ruleCOMMA]() {
					goto l2
				}
				if !_rules[ruleSpacing]() {
					goto l2
				}
				if !_rules[ruleExpr]() {
					goto l2
				}
			l4:
				{
					position5, tokenIndex5 := position, tokenIndex
					if !_rules[ruleCOMMA]() {
						goto l5
					}
					if !_rules[ruleSpacing]() {
						goto l5
					}
					if !_rules[ruleExpr]() {
						goto l5
					}
					goto l4
				l5:
					position, tokenIndex = position5, tokenIndex5
				}
				add(ruleExprList, position3)
			}
			return true
		l2:
			position, tokenIndex = position2, tokenIndex2
			return false
		},
		/* 2 Expr <- <((NotExpr / AndExpr / OrExpr / EqExpr / NeExpr / LtExpr / GtExpr / LteExpr / GteExpr / StwExpr / BtwExpr / CtnExpr / ) Spacing)> */
		func() bool {
			position6, tokenIndex6 := position, tokenIndex
			{
				position7 := position
				{
					position8, tokenIndex8 := position, tokenIndex
					if !_rules[ruleNotExpr]() {
						goto l9
					}
					goto l8
				l9:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleAndExpr]() {
						goto l10
					}
					goto l8
				l10:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleOrExpr]() {
						goto l11
					}
					goto l8
				l11:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleEqExpr]() {
						goto l12
					}
					goto l8
				l12:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleNeExpr]() {
						goto l13
					}
					goto l8
				l13:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleLtExpr]() {
						goto l14
					}
					goto l8
				l14:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleGtExpr]() {
						goto l15
					}
					goto l8
				l15:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleLteExpr]() {
						goto l16
					}
					goto l8
				l16:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleGteExpr]() {
						goto l17
					}
					goto l8
				l17:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleStwExpr]() {
						goto l18
					}
					goto l8
				l18:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleBtwExpr]() {
						goto l19
					}
					goto l8
				l19:
					position, tokenIndex = position8, tokenIndex8
					if !_rules[ruleCtnExpr]() {
						goto l20
					}
					goto l8
				l20:
					position, tokenIndex = position8, tokenIndex8
				}
			l8:
				if !_rules[ruleSpacing]() {
					goto l6
				}
				add(ruleExpr, position7)
			}
			return true
		l6:
			position, tokenIndex = position6, tokenIndex6
			return false
		},
		/* 3 NotExpr <- <(NOT LPAR Expr RPAR)> */
		func() bool {
			position21, tokenIndex21 := position, tokenIndex
			{
				position22 := position
				if !_rules[ruleNOT]() {
					goto l21
				}
				if !_rules[ruleLPAR]() {
					goto l21
				}
				if !_rules[ruleExpr]() {
					goto l21
				}
				if !_rules[ruleRPAR]() {
					goto l21
				}
				add(ruleNotExpr, position22)
			}
			return true
		l21:
			position, tokenIndex = position21, tokenIndex21
			return false
		},
		/* 4 AndExpr <- <(AND LPAR ExprList RPAR)> */
		func() bool {
			position23, tokenIndex23 := position, tokenIndex
			{
				position24 := position
				if !_rules[ruleAND]() {
					goto l23
				}
				if !_rules[ruleLPAR]() {
					goto l23
				}
				if !_rules[ruleExprList]() {
					goto l23
				}
				if !_rules[ruleRPAR]() {
					goto l23
				}
				add(ruleAndExpr, position24)
			}
			return true
		l23:
			position, tokenIndex = position23, tokenIndex23
			return false
		},
		/* 5 OrExpr <- <(OR LPAR ExprList RPAR)> */
		func() bool {
			position25, tokenIndex25 := position, tokenIndex
			{
				position26 := position
				if !_rules[ruleOR]() {
					goto l25
				}
				if !_rules[ruleLPAR]() {
					goto l25
				}
				if !_rules[ruleExprList]() {
					goto l25
				}
				if !_rules[ruleRPAR]() {
					goto l25
				}
				add(ruleOrExpr, position26)
			}
			return true
		l25:
			position, tokenIndex = position25, tokenIndex25
			return false
		},
		/* 6 EqExpr <- <(EQ LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position27, tokenIndex27 := position, tokenIndex
			{
				position28 := position
				if !_rules[ruleEQ]() {
					goto l27
				}
				if !_rules[ruleLPAR]() {
					goto l27
				}
				if !_rules[ruleIdentifier]() {
					goto l27
				}
				if !_rules[ruleCOMMA]() {
					goto l27
				}
				if !_rules[ruleLiteral]() {
					goto l27
				}
				if !_rules[ruleRPAR]() {
					goto l27
				}
				add(ruleEqExpr, position28)
			}
			return true
		l27:
			position, tokenIndex = position27, tokenIndex27
			return false
		},
		/* 7 NeExpr <- <(NE LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position29, tokenIndex29 := position, tokenIndex
			{
				position30 := position
				if !_rules[ruleNE]() {
					goto l29
				}
				if !_rules[ruleLPAR]() {
					goto l29
				}
				if !_rules[ruleIdentifier]() {
					goto l29
				}
				if !_rules[ruleCOMMA]() {
					goto l29
				}
				if !_rules[ruleLiteral]() {
					goto l29
				}
				if !_rules[ruleRPAR]() {
					goto l29
				}
				add(ruleNeExpr, position30)
			}
			return true
		l29:
			position, tokenIndex = position29, tokenIndex29
			return false
		},
		/* 8 LtExpr <- <(LT LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position31, tokenIndex31 := position, tokenIndex
			{
				position32 := position
				if !_rules[ruleLT]() {
					goto l31
				}
				if !_rules[ruleLPAR]() {
					goto l31
				}
				if !_rules[ruleIdentifier]() {
					goto l31
				}
				if !_rules[ruleCOMMA]() {
					goto l31
				}
				if !_rules[ruleLiteral]() {
					goto l31
				}
				if !_rules[ruleRPAR]() {
					goto l31
				}
				add(ruleLtExpr, position32)
			}
			return true
		l31:
			position, tokenIndex = position31, tokenIndex31
			return false
		},
		/* 9 GtExpr <- <(GT LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position33, tokenIndex33 := position, tokenIndex
			{
				position34 := position
				if !_rules[ruleGT]() {
					goto l33
				}
				if !_rules[ruleLPAR]() {
					goto l33
				}
				if !_rules[ruleIdentifier]() {
					goto l33
				}
				if !_rules[ruleCOMMA]() {
					goto l33
				}
				if !_rules[ruleLiteral]() {
					goto l33
				}
				if !_rules[ruleRPAR]() {
					goto l33
				}
				add(ruleGtExpr, position34)
			}
			return true
		l33:
			position, tokenIndex = position33, tokenIndex33
			return false
		},
		/* 10 LteExpr <- <(LTE LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position35, tokenIndex35 := position, tokenIndex
			{
				position36 := position
				if !_rules[ruleLTE]() {
					goto l35
				}
				if !_rules[ruleLPAR]() {
					goto l35
				}
				if !_rules[ruleIdentifier]() {
					goto l35
				}
				if !_rules[ruleCOMMA]() {
					goto l35
				}
				if !_rules[ruleLiteral]() {
					goto l35
				}
				if !_rules[ruleRPAR]() {
					goto l35
				}
				add(ruleLteExpr, position36)
			}
			return true
		l35:
			position, tokenIndex = position35, tokenIndex35
			return false
		},
		/* 11 GteExpr <- <(GTE LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position37, tokenIndex37 := position, tokenIndex
			{
				position38 := position
				if !_rules[ruleGTE]() {
					goto l37
				}
				if !_rules[ruleLPAR]() {
					goto l37
				}
				if !_rules[ruleIdentifier]() {
					goto l37
				}
				if !_rules[ruleCOMMA]() {
					goto l37
				}
				if !_rules[ruleLiteral]() {
					goto l37
				}
				if !_rules[ruleRPAR]() {
					goto l37
				}
				add(ruleGteExpr, position38)
			}
			return true
		l37:
			position, tokenIndex = position37, tokenIndex37
			return false
		},
		/* 12 StwExpr <- <(STW LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				if !_rules[ruleSTW]() {
					goto l39
				}
				if !_rules[ruleLPAR]() {
					goto l39
				}
				if !_rules[ruleIdentifier]() {
					goto l39
				}
				if !_rules[ruleCOMMA]() {
					goto l39
				}
				if !_rules[ruleLiteral]() {
					goto l39
				}
				if !_rules[ruleRPAR]() {
					goto l39
				}
				add(ruleStwExpr, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 13 BtwExpr <- <(BTW LPAR Identifier COMMA Literal COMMA Literal RPAR)> */
		func() bool {
			position41, tokenIndex41 := position, tokenIndex
			{
				position42 := position
				if !_rules[ruleBTW]() {
					goto l41
				}
				if !_rules[ruleLPAR]() {
					goto l41
				}
				if !_rules[ruleIdentifier]() {
					goto l41
				}
				if !_rules[ruleCOMMA]() {
					goto l41
				}
				if !_rules[ruleLiteral]() {
					goto l41
				}
				if !_rules[ruleCOMMA]() {
					goto l41
				}
				if !_rules[ruleLiteral]() {
					goto l41
				}
				if !_rules[ruleRPAR]() {
					goto l41
				}
				add(ruleBtwExpr, position42)
			}
			return true
		l41:
			position, tokenIndex = position41, tokenIndex41
			return false
		},
		/* 14 CtnExpr <- <(CTN LPAR Identifier COMMA Literal RPAR)> */
		func() bool {
			position43, tokenIndex43 := position, tokenIndex
			{
				position44 := position
				if !_rules[ruleCTN]() {
					goto l43
				}
				if !_rules[ruleLPAR]() {
					goto l43
				}
				if !_rules[ruleIdentifier]() {
					goto l43
				}
				if !_rules[ruleCOMMA]() {
					goto l43
				}
				if !_rules[ruleLiteral]() {
					goto l43
				}
				if !_rules[ruleRPAR]() {
					goto l43
				}
				add(ruleCtnExpr, position44)
			}
			return true
		l43:
			position, tokenIndex = position43, tokenIndex43
			return false
		},
		/* 15 Identifier <- <(<(IdentStart IdentCont*)> Spacing)> */
		func() bool {
			position45, tokenIndex45 := position, tokenIndex
			{
				position46 := position
				{
					position47 := position
					if !_rules[ruleIdentStart]() {
						goto l45
					}
				l48:
					{
						position49, tokenIndex49 := position, tokenIndex
						if !_rules[ruleIdentCont]() {
							goto l49
						}
						goto l48
					l49:
						position, tokenIndex = position49, tokenIndex49
					}
					add(rulePegText, position47)
				}
				if !_rules[ruleSpacing]() {
					goto l45
				}
				add(ruleIdentifier, position46)
			}
			return true
		l45:
			position, tokenIndex = position45, tokenIndex45
			return false
		},
		/* 16 IdentStart <- <([a-z] / [A-Z] / '_')> */
		func() bool {
			position50, tokenIndex50 := position, tokenIndex
			{
				position51 := position
				{
					position52, tokenIndex52 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l53
					}
					position++
					goto l52
				l53:
					position, tokenIndex = position52, tokenIndex52
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l54
					}
					position++
					goto l52
				l54:
					position, tokenIndex = position52, tokenIndex52
					if buffer[position] != rune('_') {
						goto l50
					}
					position++
				}
			l52:
				add(ruleIdentStart, position51)
			}
			return true
		l50:
			position, tokenIndex = position50, tokenIndex50
			return false
		},
		/* 17 IdentCont <- <(IdentStart / [0-9])> */
		func() bool {
			position55, tokenIndex55 := position, tokenIndex
			{
				position56 := position
				{
					position57, tokenIndex57 := position, tokenIndex
					if !_rules[ruleIdentStart]() {
						goto l58
					}
					goto l57
				l58:
					position, tokenIndex = position57, tokenIndex57
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l55
					}
					position++
				}
			l57:
				add(ruleIdentCont, position56)
			}
			return true
		l55:
			position, tokenIndex = position55, tokenIndex55
			return false
		},
		/* 18 Literal <- <(StringLiteral / NumLiteral)> */
		func() bool {
			position59, tokenIndex59 := position, tokenIndex
			{
				position60 := position
				{
					position61, tokenIndex61 := position, tokenIndex
					if !_rules[ruleStringLiteral]() {
						goto l62
					}
					goto l61
				l62:
					position, tokenIndex = position61, tokenIndex61
					if !_rules[ruleNumLiteral]() {
						goto l59
					}
				}
			l61:
				add(ruleLiteral, position60)
			}
			return true
		l59:
			position, tokenIndex = position59, tokenIndex59
			return false
		},
		/* 19 StringLiteral <- <('"' (Escape / (!('"' / '\\' / '\n' / '\r') .))* '"')> */
		func() bool {
			position63, tokenIndex63 := position, tokenIndex
			{
				position64 := position
				if buffer[position] != rune('"') {
					goto l63
				}
				position++
			l65:
				{
					position66, tokenIndex66 := position, tokenIndex
					{
						position67, tokenIndex67 := position, tokenIndex
						if !_rules[ruleEscape]() {
							goto l68
						}
						goto l67
					l68:
						position, tokenIndex = position67, tokenIndex67
						{
							position69, tokenIndex69 := position, tokenIndex
							{
								position70, tokenIndex70 := position, tokenIndex
								if buffer[position] != rune('"') {
									goto l71
								}
								position++
								goto l70
							l71:
								position, tokenIndex = position70, tokenIndex70
								if buffer[position] != rune('\\') {
									goto l72
								}
								position++
								goto l70
							l72:
								position, tokenIndex = position70, tokenIndex70
								if buffer[position] != rune('\n') {
									goto l73
								}
								position++
								goto l70
							l73:
								position, tokenIndex = position70, tokenIndex70
								if buffer[position] != rune('\r') {
									goto l69
								}
								position++
							}
						l70:
							goto l66
						l69:
							position, tokenIndex = position69, tokenIndex69
						}
						if !matchDot() {
							goto l66
						}
					}
				l67:
					goto l65
				l66:
					position, tokenIndex = position66, tokenIndex66
				}
				if buffer[position] != rune('"') {
					goto l63
				}
				position++
				add(ruleStringLiteral, position64)
			}
			return true
		l63:
			position, tokenIndex = position63, tokenIndex63
			return false
		},
		/* 20 Escape <- <('\\' ('b' / 't' / 'n' / 'f' / 'r' / '"' / '\'' / '\\' / OctalEscape / UnicodeEscape))> */
		func() bool {
			position74, tokenIndex74 := position, tokenIndex
			{
				position75 := position
				if buffer[position] != rune('\\') {
					goto l74
				}
				position++
				{
					position76, tokenIndex76 := position, tokenIndex
					if buffer[position] != rune('b') {
						goto l77
					}
					position++
					goto l76
				l77:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('t') {
						goto l78
					}
					position++
					goto l76
				l78:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('n') {
						goto l79
					}
					position++
					goto l76
				l79:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('f') {
						goto l80
					}
					position++
					goto l76
				l80:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('r') {
						goto l81
					}
					position++
					goto l76
				l81:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('"') {
						goto l82
					}
					position++
					goto l76
				l82:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('\'') {
						goto l83
					}
					position++
					goto l76
				l83:
					position, tokenIndex = position76, tokenIndex76
					if buffer[position] != rune('\\') {
						goto l84
					}
					position++
					goto l76
				l84:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[ruleOctalEscape]() {
						goto l85
					}
					goto l76
				l85:
					position, tokenIndex = position76, tokenIndex76
					if !_rules[ruleUnicodeEscape]() {
						goto l74
					}
				}
			l76:
				add(ruleEscape, position75)
			}
			return true
		l74:
			position, tokenIndex = position74, tokenIndex74
			return false
		},
		/* 21 OctalEscape <- <(([0-3] [0-7] [0-7]) / ([0-7] [0-7]) / [0-7])> */
		func() bool {
			position86, tokenIndex86 := position, tokenIndex
			{
				position87 := position
				{
					position88, tokenIndex88 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('3') {
						goto l89
					}
					position++
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l89
					}
					position++
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l89
					}
					position++
					goto l88
				l89:
					position, tokenIndex = position88, tokenIndex88
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l90
					}
					position++
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l90
					}
					position++
					goto l88
				l90:
					position, tokenIndex = position88, tokenIndex88
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l86
					}
					position++
				}
			l88:
				add(ruleOctalEscape, position87)
			}
			return true
		l86:
			position, tokenIndex = position86, tokenIndex86
			return false
		},
		/* 22 UnicodeEscape <- <('u'+ HexDigit HexDigit HexDigit HexDigit)> */
		func() bool {
			position91, tokenIndex91 := position, tokenIndex
			{
				position92 := position
				if buffer[position] != rune('u') {
					goto l91
				}
				position++
			l93:
				{
					position94, tokenIndex94 := position, tokenIndex
					if buffer[position] != rune('u') {
						goto l94
					}
					position++
					goto l93
				l94:
					position, tokenIndex = position94, tokenIndex94
				}
				if !_rules[ruleHexDigit]() {
					goto l91
				}
				if !_rules[ruleHexDigit]() {
					goto l91
				}
				if !_rules[ruleHexDigit]() {
					goto l91
				}
				if !_rules[ruleHexDigit]() {
					goto l91
				}
				add(ruleUnicodeEscape, position92)
			}
			return true
		l91:
			position, tokenIndex = position91, tokenIndex91
			return false
		},
		/* 23 NumLiteral <- <((Digits '.' Digits?) / Digits)> */
		func() bool {
			position95, tokenIndex95 := position, tokenIndex
			{
				position96 := position
				{
					position97, tokenIndex97 := position, tokenIndex
					if !_rules[ruleDigits]() {
						goto l98
					}
					if buffer[position] != rune('.') {
						goto l98
					}
					position++
					{
						position99, tokenIndex99 := position, tokenIndex
						if !_rules[ruleDigits]() {
							goto l99
						}
						goto l100
					l99:
						position, tokenIndex = position99, tokenIndex99
					}
				l100:
					goto l97
				l98:
					position, tokenIndex = position97, tokenIndex97
					if !_rules[ruleDigits]() {
						goto l95
					}
				}
			l97:
				add(ruleNumLiteral, position96)
			}
			return true
		l95:
			position, tokenIndex = position95, tokenIndex95
			return false
		},
		/* 24 Digits <- <([0-9] ('_'* [0-9])*)> */
		func() bool {
			position101, tokenIndex101 := position, tokenIndex
			{
				position102 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l101
				}
				position++
			l103:
				{
					position104, tokenIndex104 := position, tokenIndex
				l105:
					{
						position106, tokenIndex106 := position, tokenIndex
						if buffer[position] != rune('_') {
							goto l106
						}
						position++
						goto l105
					l106:
						position, tokenIndex = position106, tokenIndex106
					}
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l104
					}
					position++
					goto l103
				l104:
					position, tokenIndex = position104, tokenIndex104
				}
				add(ruleDigits, position102)
			}
			return true
		l101:
			position, tokenIndex = position101, tokenIndex101
			return false
		},
		/* 25 HexDigit <- <([a-f] / [A-F] / [0-9])> */
		func() bool {
			position107, tokenIndex107 := position, tokenIndex
			{
				position108 := position
				{
					position109, tokenIndex109 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('f') {
						goto l110
					}
					position++
					goto l109
				l110:
					position, tokenIndex = position109, tokenIndex109
					if c := buffer[position]; c < rune('A') || c > rune('F') {
						goto l111
					}
					position++
					goto l109
				l111:
					position, tokenIndex = position109, tokenIndex109
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l107
					}
					position++
				}
			l109:
				add(ruleHexDigit, position108)
			}
			return true
		l107:
			position, tokenIndex = position107, tokenIndex107
			return false
		},
		/* 26 NOT <- <('n' 'o' 't' Spacing)> */
		func() bool {
			position112, tokenIndex112 := position, tokenIndex
			{
				position113 := position
				if buffer[position] != rune('n') {
					goto l112
				}
				position++
				if buffer[position] != rune('o') {
					goto l112
				}
				position++
				if buffer[position] != rune('t') {
					goto l112
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l112
				}
				add(ruleNOT, position113)
			}
			return true
		l112:
			position, tokenIndex = position112, tokenIndex112
			return false
		},
		/* 27 AND <- <('a' 'n' 'd' Spacing)> */
		func() bool {
			position114, tokenIndex114 := position, tokenIndex
			{
				position115 := position
				if buffer[position] != rune('a') {
					goto l114
				}
				position++
				if buffer[position] != rune('n') {
					goto l114
				}
				position++
				if buffer[position] != rune('d') {
					goto l114
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l114
				}
				add(ruleAND, position115)
			}
			return true
		l114:
			position, tokenIndex = position114, tokenIndex114
			return false
		},
		/* 28 OR <- <('o' 'r' Spacing)> */
		func() bool {
			position116, tokenIndex116 := position, tokenIndex
			{
				position117 := position
				if buffer[position] != rune('o') {
					goto l116
				}
				position++
				if buffer[position] != rune('r') {
					goto l116
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l116
				}
				add(ruleOR, position117)
			}
			return true
		l116:
			position, tokenIndex = position116, tokenIndex116
			return false
		},
		/* 29 EQ <- <('e' 'q' Spacing)> */
		func() bool {
			position118, tokenIndex118 := position, tokenIndex
			{
				position119 := position
				if buffer[position] != rune('e') {
					goto l118
				}
				position++
				if buffer[position] != rune('q') {
					goto l118
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l118
				}
				add(ruleEQ, position119)
			}
			return true
		l118:
			position, tokenIndex = position118, tokenIndex118
			return false
		},
		/* 30 NE <- <('n' 'e' Spacing)> */
		func() bool {
			position120, tokenIndex120 := position, tokenIndex
			{
				position121 := position
				if buffer[position] != rune('n') {
					goto l120
				}
				position++
				if buffer[position] != rune('e') {
					goto l120
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l120
				}
				add(ruleNE, position121)
			}
			return true
		l120:
			position, tokenIndex = position120, tokenIndex120
			return false
		},
		/* 31 LT <- <('l' 't' Spacing)> */
		func() bool {
			position122, tokenIndex122 := position, tokenIndex
			{
				position123 := position
				if buffer[position] != rune('l') {
					goto l122
				}
				position++
				if buffer[position] != rune('t') {
					goto l122
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l122
				}
				add(ruleLT, position123)
			}
			return true
		l122:
			position, tokenIndex = position122, tokenIndex122
			return false
		},
		/* 32 GT <- <('g' 't' Spacing)> */
		func() bool {
			position124, tokenIndex124 := position, tokenIndex
			{
				position125 := position
				if buffer[position] != rune('g') {
					goto l124
				}
				position++
				if buffer[position] != rune('t') {
					goto l124
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l124
				}
				add(ruleGT, position125)
			}
			return true
		l124:
			position, tokenIndex = position124, tokenIndex124
			return false
		},
		/* 33 LTE <- <('l' 't' 'e' Spacing)> */
		func() bool {
			position126, tokenIndex126 := position, tokenIndex
			{
				position127 := position
				if buffer[position] != rune('l') {
					goto l126
				}
				position++
				if buffer[position] != rune('t') {
					goto l126
				}
				position++
				if buffer[position] != rune('e') {
					goto l126
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l126
				}
				add(ruleLTE, position127)
			}
			return true
		l126:
			position, tokenIndex = position126, tokenIndex126
			return false
		},
		/* 34 GTE <- <('g' 't' 'e' Spacing)> */
		func() bool {
			position128, tokenIndex128 := position, tokenIndex
			{
				position129 := position
				if buffer[position] != rune('g') {
					goto l128
				}
				position++
				if buffer[position] != rune('t') {
					goto l128
				}
				position++
				if buffer[position] != rune('e') {
					goto l128
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l128
				}
				add(ruleGTE, position129)
			}
			return true
		l128:
			position, tokenIndex = position128, tokenIndex128
			return false
		},
		/* 35 BTW <- <('b' 't' 'w' Spacing)> */
		func() bool {
			position130, tokenIndex130 := position, tokenIndex
			{
				position131 := position
				if buffer[position] != rune('b') {
					goto l130
				}
				position++
				if buffer[position] != rune('t') {
					goto l130
				}
				position++
				if buffer[position] != rune('w') {
					goto l130
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l130
				}
				add(ruleBTW, position131)
			}
			return true
		l130:
			position, tokenIndex = position130, tokenIndex130
			return false
		},
		/* 36 STW <- <('s' 't' 'w' Spacing)> */
		func() bool {
			position132, tokenIndex132 := position, tokenIndex
			{
				position133 := position
				if buffer[position] != rune('s') {
					goto l132
				}
				position++
				if buffer[position] != rune('t') {
					goto l132
				}
				position++
				if buffer[position] != rune('w') {
					goto l132
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l132
				}
				add(ruleSTW, position133)
			}
			return true
		l132:
			position, tokenIndex = position132, tokenIndex132
			return false
		},
		/* 37 CTN <- <('c' 't' 'n' Spacing)> */
		func() bool {
			position134, tokenIndex134 := position, tokenIndex
			{
				position135 := position
				if buffer[position] != rune('c') {
					goto l134
				}
				position++
				if buffer[position] != rune('t') {
					goto l134
				}
				position++
				if buffer[position] != rune('n') {
					goto l134
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l134
				}
				add(ruleCTN, position135)
			}
			return true
		l134:
			position, tokenIndex = position134, tokenIndex134
			return false
		},
		/* 38 LPAR <- <('(' Spacing)> */
		func() bool {
			position136, tokenIndex136 := position, tokenIndex
			{
				position137 := position
				if buffer[position] != rune('(') {
					goto l136
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l136
				}
				add(ruleLPAR, position137)
			}
			return true
		l136:
			position, tokenIndex = position136, tokenIndex136
			return false
		},
		/* 39 RPAR <- <(')' Spacing)> */
		func() bool {
			position138, tokenIndex138 := position, tokenIndex
			{
				position139 := position
				if buffer[position] != rune(')') {
					goto l138
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l138
				}
				add(ruleRPAR, position139)
			}
			return true
		l138:
			position, tokenIndex = position138, tokenIndex138
			return false
		},
		/* 40 COMMA <- <(',' Spacing)> */
		func() bool {
			position140, tokenIndex140 := position, tokenIndex
			{
				position141 := position
				if buffer[position] != rune(',') {
					goto l140
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l140
				}
				add(ruleCOMMA, position141)
			}
			return true
		l140:
			position, tokenIndex = position140, tokenIndex140
			return false
		},
		/* 41 Spacing <- <(' ' / '\t')*> */
		func() bool {
			{
				position143 := position
			l144:
				{
					position145, tokenIndex145 := position, tokenIndex
					{
						position146, tokenIndex146 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l147
						}
						position++
						goto l146
					l147:
						position, tokenIndex = position146, tokenIndex146
						if buffer[position] != rune('\t') {
							goto l145
						}
						position++
					}
				l146:
					goto l144
				l145:
					position, tokenIndex = position145, tokenIndex145
				}
				add(ruleSpacing, position143)
			}
			return true
		},
		/* 42 EOT <- <!.> */
		func() bool {
			position148, tokenIndex148 := position, tokenIndex
			{
				position149 := position
				{
					position150, tokenIndex150 := position, tokenIndex
					if !matchDot() {
						goto l150
					}
					goto l148
				l150:
					position, tokenIndex = position150, tokenIndex150
				}
				add(ruleEOT, position149)
			}
			return true
		l148:
			position, tokenIndex = position148, tokenIndex148
			return false
		},
		nil,
	}
	p.rules = _rules
	return nil
}
