package filterable

// Code generated by peg -output internal/common/data/filterable/filterable_ast.go internal/common/data/filterable/filterable.peg DO NOT EDIT.

import (
	"fmt"
	"io"
	"os"
	"sort"
	"strconv"
	"strings"
)

const endSymbol rune = 1114112

/* The rule types inferred from the grammar are below. */
type pegRule uint8

const (
	ruleUnknown pegRule = iota
	ruleF
	ruleF1
	ruleF2
	ruleF3
	ruleF4
	ruleAtomFilter
	ruleOperator
	ruleField
	ruleIdentifier
	ruleIdentStart
	ruleIdentCont
	ruleValues
	ruleValueList
	ruleSingleValue
	ruleStringLiteral
	ruleStringChar
	ruleEscape
	ruleUniversalCharacter
	ruleHexQuad
	ruleSimpleEscape
	ruleOctalEscape
	ruleHexEscape
	ruleHexDigit
	ruleNumLiteral
	ruleDigits
	ruleNOT
	ruleAND
	ruleOR
	ruleEQ
	ruleNE
	ruleLT
	ruleGT
	ruleLTE
	ruleGTE
	ruleBTW
	ruleSTW
	ruleCTN
	ruleLBRK
	ruleRBRK
	ruleLPAR
	ruleRPAR
	ruleCOMMA
	ruleSpacing
	ruleEOT
	rulePegText
)

var rul3s = [...]string{
	"Unknown",
	"F",
	"F1",
	"F2",
	"F3",
	"F4",
	"AtomFilter",
	"Operator",
	"Field",
	"Identifier",
	"IdentStart",
	"IdentCont",
	"Values",
	"ValueList",
	"SingleValue",
	"StringLiteral",
	"StringChar",
	"Escape",
	"UniversalCharacter",
	"HexQuad",
	"SimpleEscape",
	"OctalEscape",
	"HexEscape",
	"HexDigit",
	"NumLiteral",
	"Digits",
	"NOT",
	"AND",
	"OR",
	"EQ",
	"NE",
	"LT",
	"GT",
	"LTE",
	"GTE",
	"BTW",
	"STW",
	"CTN",
	"LBRK",
	"RBRK",
	"LPAR",
	"RPAR",
	"COMMA",
	"Spacing",
	"EOT",
	"PegText",
}

type token32 struct {
	pegRule
	begin, end uint32
}

func (t *token32) String() string {
	return fmt.Sprintf("\x1B[34m%v\x1B[m %v %v", rul3s[t.pegRule], t.begin, t.end)
}

type node32 struct {
	token32
	up, next *node32
}

func (node *node32) print(w io.Writer, pretty bool, buffer string) {
	var print func(node *node32, depth int)
	print = func(node *node32, depth int) {
		for node != nil {
			for c := 0; c < depth; c++ {
				fmt.Fprintf(w, " ")
			}
			rule := rul3s[node.pegRule]
			quote := strconv.Quote(string(([]rune(buffer)[node.begin:node.end])))
			if !pretty {
				fmt.Fprintf(w, "%v %v\n", rule, quote)
			} else {
				fmt.Fprintf(w, "\x1B[36m%v\x1B[m %v\n", rule, quote)
			}
			if node.up != nil {
				print(node.up, depth+1)
			}
			node = node.next
		}
	}
	print(node, 0)
}

func (node *node32) Print(w io.Writer, buffer string) {
	node.print(w, false, buffer)
}

func (node *node32) PrettyPrint(w io.Writer, buffer string) {
	node.print(w, true, buffer)
}

type tokens32 struct {
	tree []token32
}

func (t *tokens32) Trim(length uint32) {
	t.tree = t.tree[:length]
}

func (t *tokens32) Print() {
	for _, token := range t.tree {
		fmt.Println(token.String())
	}
}

func (t *tokens32) AST() *node32 {
	type element struct {
		node *node32
		down *element
	}
	tokens := t.Tokens()
	var stack *element
	for _, token := range tokens {
		if token.begin == token.end {
			continue
		}
		node := &node32{token32: token}
		for stack != nil && stack.node.begin >= token.begin && stack.node.end <= token.end {
			stack.node.next = node.up
			node.up = stack.node
			stack = stack.down
		}
		stack = &element{node: node, down: stack}
	}
	if stack != nil {
		return stack.node
	}
	return nil
}

func (t *tokens32) PrintSyntaxTree(buffer string) {
	t.AST().Print(os.Stdout, buffer)
}

func (t *tokens32) WriteSyntaxTree(w io.Writer, buffer string) {
	t.AST().Print(w, buffer)
}

func (t *tokens32) PrettyPrintSyntaxTree(buffer string) {
	t.AST().PrettyPrint(os.Stdout, buffer)
}

func (t *tokens32) Add(rule pegRule, begin, end, index uint32) {
	tree, i := t.tree, int(index)
	if i >= len(tree) {
		t.tree = append(tree, token32{pegRule: rule, begin: begin, end: end})
		return
	}
	tree[i] = token32{pegRule: rule, begin: begin, end: end}
}

func (t *tokens32) Tokens() []token32 {
	return t.tree
}

type FilterExpr struct {
	Buffer string
	buffer []rune
	rules  [46]func() bool
	parse  func(rule ...int) error
	reset  func()
	Pretty bool
	tokens32
}

func (p *FilterExpr) Parse(rule ...int) error {
	return p.parse(rule...)
}

func (p *FilterExpr) Reset() {
	p.reset()
}

type textPosition struct {
	line, symbol int
}

type textPositionMap map[int]textPosition

func translatePositions(buffer []rune, positions []int) textPositionMap {
	length, translations, j, line, symbol := len(positions), make(textPositionMap, len(positions)), 0, 1, 0
	sort.Ints(positions)

search:
	for i, c := range buffer {
		if c == '\n' {
			line, symbol = line+1, 0
		} else {
			symbol++
		}
		if i == positions[j] {
			translations[positions[j]] = textPosition{line, symbol}
			for j++; j < length; j++ {
				if i != positions[j] {
					continue search
				}
			}
			break search
		}
	}

	return translations
}

type parseError struct {
	p   *FilterExpr
	max token32
}

func (e *parseError) Error() string {
	tokens, err := []token32{e.max}, "\n"
	positions, p := make([]int, 2*len(tokens)), 0
	for _, token := range tokens {
		positions[p], p = int(token.begin), p+1
		positions[p], p = int(token.end), p+1
	}
	translations := translatePositions(e.p.buffer, positions)
	format := "parse error near %v (line %v symbol %v - line %v symbol %v):\n%v\n"
	if e.p.Pretty {
		format = "parse error near \x1B[34m%v\x1B[m (line %v symbol %v - line %v symbol %v):\n%v\n"
	}
	for _, token := range tokens {
		begin, end := int(token.begin), int(token.end)
		err += fmt.Sprintf(format,
			rul3s[token.pegRule],
			translations[begin].line, translations[begin].symbol,
			translations[end].line, translations[end].symbol,
			strconv.Quote(string(e.p.buffer[begin:end])))
	}

	return err
}

func (p *FilterExpr) PrintSyntaxTree() {
	if p.Pretty {
		p.tokens32.PrettyPrintSyntaxTree(p.Buffer)
	} else {
		p.tokens32.PrintSyntaxTree(p.Buffer)
	}
}

func (p *FilterExpr) WriteSyntaxTree(w io.Writer) {
	p.tokens32.WriteSyntaxTree(w, p.Buffer)
}

func (p *FilterExpr) SprintSyntaxTree() string {
	var bldr strings.Builder
	p.WriteSyntaxTree(&bldr)
	return bldr.String()
}

func Pretty(pretty bool) func(*FilterExpr) error {
	return func(p *FilterExpr) error {
		p.Pretty = pretty
		return nil
	}
}

func Size(size int) func(*FilterExpr) error {
	return func(p *FilterExpr) error {
		p.tokens32 = tokens32{tree: make([]token32, 0, size)}
		return nil
	}
}
func (p *FilterExpr) Init(options ...func(*FilterExpr) error) error {
	var (
		max                  token32
		position, tokenIndex uint32
		buffer               []rune
	)
	for _, option := range options {
		err := option(p)
		if err != nil {
			return err
		}
	}
	p.reset = func() {
		max = token32{}
		position, tokenIndex = 0, 0

		p.buffer = []rune(p.Buffer)
		if len(p.buffer) == 0 || p.buffer[len(p.buffer)-1] != endSymbol {
			p.buffer = append(p.buffer, endSymbol)
		}
		buffer = p.buffer
	}
	p.reset()

	_rules := p.rules
	tree := p.tokens32
	p.parse = func(rule ...int) error {
		r := 1
		if len(rule) > 0 {
			r = rule[0]
		}
		matches := p.rules[r]()
		p.tokens32 = tree
		if matches {
			p.Trim(tokenIndex)
			return nil
		}
		return &parseError{p, max}
	}

	add := func(rule pegRule, begin uint32) {
		tree.Add(rule, begin, position, tokenIndex)
		tokenIndex++
		if begin != position && position > max.end {
			max = token32{rule, begin, position}
		}
	}

	matchDot := func() bool {
		if buffer[position] != endSymbol {
			position++
			return true
		}
		return false
	}

	/*matchChar := func(c byte) bool {
		if buffer[position] == c {
			position++
			return true
		}
		return false
	}*/

	/*matchRange := func(lower byte, upper byte) bool {
		if c := buffer[position]; c >= lower && c <= upper {
			position++
			return true
		}
		return false
	}*/

	_rules = [...]func() bool{
		nil,
		/* 0 F <- <(Spacing F1 EOT)> */
		func() bool {
			position0, tokenIndex0 := position, tokenIndex
			{
				position1 := position
				if !_rules[ruleSpacing]() {
					goto l0
				}
				if !_rules[ruleF1]() {
					goto l0
				}
				if !_rules[ruleEOT]() {
					goto l0
				}
				add(ruleF, position1)
			}
			return true
		l0:
			position, tokenIndex = position0, tokenIndex0
			return false
		},
		/* 1 F1 <- <(F2 (OR F2)*)> */
		func() bool {
			position2, tokenIndex2 := position, tokenIndex
			{
				position3 := position
				if !_rules[ruleF2]() {
					goto l2
				}
			l4:
				{
					position5, tokenIndex5 := position, tokenIndex
					if !_rules[ruleOR]() {
						goto l5
					}
					if !_rules[ruleF2]() {
						goto l5
					}
					goto l4
				l5:
					position, tokenIndex = position5, tokenIndex5
				}
				add(ruleF1, position3)
			}
			return true
		l2:
			position, tokenIndex = position2, tokenIndex2
			return false
		},
		/* 2 F2 <- <(F3 (AND F3)*)> */
		func() bool {
			position6, tokenIndex6 := position, tokenIndex
			{
				position7 := position
				if !_rules[ruleF3]() {
					goto l6
				}
			l8:
				{
					position9, tokenIndex9 := position, tokenIndex
					if !_rules[ruleAND]() {
						goto l9
					}
					if !_rules[ruleF3]() {
						goto l9
					}
					goto l8
				l9:
					position, tokenIndex = position9, tokenIndex9
				}
				add(ruleF2, position7)
			}
			return true
		l6:
			position, tokenIndex = position6, tokenIndex6
			return false
		},
		/* 3 F3 <- <((NOT F4) / F4)> */
		func() bool {
			position10, tokenIndex10 := position, tokenIndex
			{
				position11 := position
				{
					position12, tokenIndex12 := position, tokenIndex
					if !_rules[ruleNOT]() {
						goto l13
					}
					if !_rules[ruleF4]() {
						goto l13
					}
					goto l12
				l13:
					position, tokenIndex = position12, tokenIndex12
					if !_rules[ruleF4]() {
						goto l10
					}
				}
			l12:
				add(ruleF3, position11)
			}
			return true
		l10:
			position, tokenIndex = position10, tokenIndex10
			return false
		},
		/* 4 F4 <- <(AtomFilter / (LPAR F1 RPAR))> */
		func() bool {
			position14, tokenIndex14 := position, tokenIndex
			{
				position15 := position
				{
					position16, tokenIndex16 := position, tokenIndex
					if !_rules[ruleAtomFilter]() {
						goto l17
					}
					goto l16
				l17:
					position, tokenIndex = position16, tokenIndex16
					if !_rules[ruleLPAR]() {
						goto l14
					}
					if !_rules[ruleF1]() {
						goto l14
					}
					if !_rules[ruleRPAR]() {
						goto l14
					}
				}
			l16:
				add(ruleF4, position15)
			}
			return true
		l14:
			position, tokenIndex = position14, tokenIndex14
			return false
		},
		/* 5 AtomFilter <- <(Field Operator Values)> */
		func() bool {
			position18, tokenIndex18 := position, tokenIndex
			{
				position19 := position
				if !_rules[ruleField]() {
					goto l18
				}
				if !_rules[ruleOperator]() {
					goto l18
				}
				if !_rules[ruleValues]() {
					goto l18
				}
				add(ruleAtomFilter, position19)
			}
			return true
		l18:
			position, tokenIndex = position18, tokenIndex18
			return false
		},
		/* 6 Operator <- <((EQ / NE / LTE / GTE / LT / GT / STW / BTW / CTN / ) Spacing)> */
		func() bool {
			position20, tokenIndex20 := position, tokenIndex
			{
				position21 := position
				{
					position22, tokenIndex22 := position, tokenIndex
					if !_rules[ruleEQ]() {
						goto l23
					}
					goto l22
				l23:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleNE]() {
						goto l24
					}
					goto l22
				l24:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleLTE]() {
						goto l25
					}
					goto l22
				l25:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleGTE]() {
						goto l26
					}
					goto l22
				l26:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleLT]() {
						goto l27
					}
					goto l22
				l27:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleGT]() {
						goto l28
					}
					goto l22
				l28:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleSTW]() {
						goto l29
					}
					goto l22
				l29:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleBTW]() {
						goto l30
					}
					goto l22
				l30:
					position, tokenIndex = position22, tokenIndex22
					if !_rules[ruleCTN]() {
						goto l31
					}
					goto l22
				l31:
					position, tokenIndex = position22, tokenIndex22
				}
			l22:
				if !_rules[ruleSpacing]() {
					goto l20
				}
				add(ruleOperator, position21)
			}
			return true
		l20:
			position, tokenIndex = position20, tokenIndex20
			return false
		},
		/* 7 Field <- <Identifier> */
		func() bool {
			position32, tokenIndex32 := position, tokenIndex
			{
				position33 := position
				if !_rules[ruleIdentifier]() {
					goto l32
				}
				add(ruleField, position33)
			}
			return true
		l32:
			position, tokenIndex = position32, tokenIndex32
			return false
		},
		/* 8 Identifier <- <(<(IdentStart IdentCont*)> Spacing)> */
		func() bool {
			position34, tokenIndex34 := position, tokenIndex
			{
				position35 := position
				{
					position36 := position
					if !_rules[ruleIdentStart]() {
						goto l34
					}
				l37:
					{
						position38, tokenIndex38 := position, tokenIndex
						if !_rules[ruleIdentCont]() {
							goto l38
						}
						goto l37
					l38:
						position, tokenIndex = position38, tokenIndex38
					}
					add(rulePegText, position36)
				}
				if !_rules[ruleSpacing]() {
					goto l34
				}
				add(ruleIdentifier, position35)
			}
			return true
		l34:
			position, tokenIndex = position34, tokenIndex34
			return false
		},
		/* 9 IdentStart <- <([a-z] / [A-Z] / '_')> */
		func() bool {
			position39, tokenIndex39 := position, tokenIndex
			{
				position40 := position
				{
					position41, tokenIndex41 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('z') {
						goto l42
					}
					position++
					goto l41
				l42:
					position, tokenIndex = position41, tokenIndex41
					if c := buffer[position]; c < rune('A') || c > rune('Z') {
						goto l43
					}
					position++
					goto l41
				l43:
					position, tokenIndex = position41, tokenIndex41
					if buffer[position] != rune('_') {
						goto l39
					}
					position++
				}
			l41:
				add(ruleIdentStart, position40)
			}
			return true
		l39:
			position, tokenIndex = position39, tokenIndex39
			return false
		},
		/* 10 IdentCont <- <(IdentStart / [0-9])> */
		func() bool {
			position44, tokenIndex44 := position, tokenIndex
			{
				position45 := position
				{
					position46, tokenIndex46 := position, tokenIndex
					if !_rules[ruleIdentStart]() {
						goto l47
					}
					goto l46
				l47:
					position, tokenIndex = position46, tokenIndex46
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l44
					}
					position++
				}
			l46:
				add(ruleIdentCont, position45)
			}
			return true
		l44:
			position, tokenIndex = position44, tokenIndex44
			return false
		},
		/* 11 Values <- <((ValueList / SingleValue) Spacing)> */
		func() bool {
			position48, tokenIndex48 := position, tokenIndex
			{
				position49 := position
				{
					position50, tokenIndex50 := position, tokenIndex
					if !_rules[ruleValueList]() {
						goto l51
					}
					goto l50
				l51:
					position, tokenIndex = position50, tokenIndex50
					if !_rules[ruleSingleValue]() {
						goto l48
					}
				}
			l50:
				if !_rules[ruleSpacing]() {
					goto l48
				}
				add(ruleValues, position49)
			}
			return true
		l48:
			position, tokenIndex = position48, tokenIndex48
			return false
		},
		/* 12 ValueList <- <(LBRK (SingleValue Spacing COMMA)* SingleValue RBRK)> */
		func() bool {
			position52, tokenIndex52 := position, tokenIndex
			{
				position53 := position
				if !_rules[ruleLBRK]() {
					goto l52
				}
			l54:
				{
					position55, tokenIndex55 := position, tokenIndex
					if !_rules[ruleSingleValue]() {
						goto l55
					}
					if !_rules[ruleSpacing]() {
						goto l55
					}
					if !_rules[ruleCOMMA]() {
						goto l55
					}
					goto l54
				l55:
					position, tokenIndex = position55, tokenIndex55
				}
				if !_rules[ruleSingleValue]() {
					goto l52
				}
				if !_rules[ruleRBRK]() {
					goto l52
				}
				add(ruleValueList, position53)
			}
			return true
		l52:
			position, tokenIndex = position52, tokenIndex52
			return false
		},
		/* 13 SingleValue <- <(StringLiteral / NumLiteral)> */
		func() bool {
			position56, tokenIndex56 := position, tokenIndex
			{
				position57 := position
				{
					position58, tokenIndex58 := position, tokenIndex
					if !_rules[ruleStringLiteral]() {
						goto l59
					}
					goto l58
				l59:
					position, tokenIndex = position58, tokenIndex58
					if !_rules[ruleNumLiteral]() {
						goto l56
					}
				}
			l58:
				add(ruleSingleValue, position57)
			}
			return true
		l56:
			position, tokenIndex = position56, tokenIndex56
			return false
		},
		/* 14 StringLiteral <- <('L'? ('"' StringChar* '"' Spacing)+)> */
		func() bool {
			position60, tokenIndex60 := position, tokenIndex
			{
				position61 := position
				{
					position62, tokenIndex62 := position, tokenIndex
					if buffer[position] != rune('L') {
						goto l62
					}
					position++
					goto l63
				l62:
					position, tokenIndex = position62, tokenIndex62
				}
			l63:
				if buffer[position] != rune('"') {
					goto l60
				}
				position++
			l66:
				{
					position67, tokenIndex67 := position, tokenIndex
					if !_rules[ruleStringChar]() {
						goto l67
					}
					goto l66
				l67:
					position, tokenIndex = position67, tokenIndex67
				}
				if buffer[position] != rune('"') {
					goto l60
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l60
				}
			l64:
				{
					position65, tokenIndex65 := position, tokenIndex
					if buffer[position] != rune('"') {
						goto l65
					}
					position++
				l68:
					{
						position69, tokenIndex69 := position, tokenIndex
						if !_rules[ruleStringChar]() {
							goto l69
						}
						goto l68
					l69:
						position, tokenIndex = position69, tokenIndex69
					}
					if buffer[position] != rune('"') {
						goto l65
					}
					position++
					if !_rules[ruleSpacing]() {
						goto l65
					}
					goto l64
				l65:
					position, tokenIndex = position65, tokenIndex65
				}
				add(ruleStringLiteral, position61)
			}
			return true
		l60:
			position, tokenIndex = position60, tokenIndex60
			return false
		},
		/* 15 StringChar <- <(Escape / (!('"' / '\n' / '\\') .))> */
		func() bool {
			position70, tokenIndex70 := position, tokenIndex
			{
				position71 := position
				{
					position72, tokenIndex72 := position, tokenIndex
					if !_rules[ruleEscape]() {
						goto l73
					}
					goto l72
				l73:
					position, tokenIndex = position72, tokenIndex72
					{
						position74, tokenIndex74 := position, tokenIndex
						{
							position75, tokenIndex75 := position, tokenIndex
							if buffer[position] != rune('"') {
								goto l76
							}
							position++
							goto l75
						l76:
							position, tokenIndex = position75, tokenIndex75
							if buffer[position] != rune('\n') {
								goto l77
							}
							position++
							goto l75
						l77:
							position, tokenIndex = position75, tokenIndex75
							if buffer[position] != rune('\\') {
								goto l74
							}
							position++
						}
					l75:
						goto l70
					l74:
						position, tokenIndex = position74, tokenIndex74
					}
					if !matchDot() {
						goto l70
					}
				}
			l72:
				add(ruleStringChar, position71)
			}
			return true
		l70:
			position, tokenIndex = position70, tokenIndex70
			return false
		},
		/* 16 Escape <- <(SimpleEscape / OctalEscape / HexEscape / UniversalCharacter)> */
		func() bool {
			position78, tokenIndex78 := position, tokenIndex
			{
				position79 := position
				{
					position80, tokenIndex80 := position, tokenIndex
					if !_rules[ruleSimpleEscape]() {
						goto l81
					}
					goto l80
				l81:
					position, tokenIndex = position80, tokenIndex80
					if !_rules[ruleOctalEscape]() {
						goto l82
					}
					goto l80
				l82:
					position, tokenIndex = position80, tokenIndex80
					if !_rules[ruleHexEscape]() {
						goto l83
					}
					goto l80
				l83:
					position, tokenIndex = position80, tokenIndex80
					if !_rules[ruleUniversalCharacter]() {
						goto l78
					}
				}
			l80:
				add(ruleEscape, position79)
			}
			return true
		l78:
			position, tokenIndex = position78, tokenIndex78
			return false
		},
		/* 17 UniversalCharacter <- <(('\\' 'u' HexQuad) / ('\\' 'U' HexQuad HexQuad))> */
		func() bool {
			position84, tokenIndex84 := position, tokenIndex
			{
				position85 := position
				{
					position86, tokenIndex86 := position, tokenIndex
					if buffer[position] != rune('\\') {
						goto l87
					}
					position++
					if buffer[position] != rune('u') {
						goto l87
					}
					position++
					if !_rules[ruleHexQuad]() {
						goto l87
					}
					goto l86
				l87:
					position, tokenIndex = position86, tokenIndex86
					if buffer[position] != rune('\\') {
						goto l84
					}
					position++
					if buffer[position] != rune('U') {
						goto l84
					}
					position++
					if !_rules[ruleHexQuad]() {
						goto l84
					}
					if !_rules[ruleHexQuad]() {
						goto l84
					}
				}
			l86:
				add(ruleUniversalCharacter, position85)
			}
			return true
		l84:
			position, tokenIndex = position84, tokenIndex84
			return false
		},
		/* 18 HexQuad <- <(HexDigit HexDigit HexDigit HexDigit)> */
		func() bool {
			position88, tokenIndex88 := position, tokenIndex
			{
				position89 := position
				if !_rules[ruleHexDigit]() {
					goto l88
				}
				if !_rules[ruleHexDigit]() {
					goto l88
				}
				if !_rules[ruleHexDigit]() {
					goto l88
				}
				if !_rules[ruleHexDigit]() {
					goto l88
				}
				add(ruleHexQuad, position89)
			}
			return true
		l88:
			position, tokenIndex = position88, tokenIndex88
			return false
		},
		/* 19 SimpleEscape <- <('\\' ('\'' / '"' / '?' / '\\' / '%' / 'a' / 'b' / 'f' / 'n' / 'r' / 't' / 'v'))> */
		func() bool {
			position90, tokenIndex90 := position, tokenIndex
			{
				position91 := position
				if buffer[position] != rune('\\') {
					goto l90
				}
				position++
				{
					position92, tokenIndex92 := position, tokenIndex
					if buffer[position] != rune('\'') {
						goto l93
					}
					position++
					goto l92
				l93:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('"') {
						goto l94
					}
					position++
					goto l92
				l94:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('?') {
						goto l95
					}
					position++
					goto l92
				l95:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('\\') {
						goto l96
					}
					position++
					goto l92
				l96:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('%') {
						goto l97
					}
					position++
					goto l92
				l97:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('a') {
						goto l98
					}
					position++
					goto l92
				l98:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('b') {
						goto l99
					}
					position++
					goto l92
				l99:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('f') {
						goto l100
					}
					position++
					goto l92
				l100:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('n') {
						goto l101
					}
					position++
					goto l92
				l101:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('r') {
						goto l102
					}
					position++
					goto l92
				l102:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('t') {
						goto l103
					}
					position++
					goto l92
				l103:
					position, tokenIndex = position92, tokenIndex92
					if buffer[position] != rune('v') {
						goto l90
					}
					position++
				}
			l92:
				add(ruleSimpleEscape, position91)
			}
			return true
		l90:
			position, tokenIndex = position90, tokenIndex90
			return false
		},
		/* 20 OctalEscape <- <('\\' [0-7] [0-7]? [0-7]?)> */
		func() bool {
			position104, tokenIndex104 := position, tokenIndex
			{
				position105 := position
				if buffer[position] != rune('\\') {
					goto l104
				}
				position++
				if c := buffer[position]; c < rune('0') || c > rune('7') {
					goto l104
				}
				position++
				{
					position106, tokenIndex106 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l106
					}
					position++
					goto l107
				l106:
					position, tokenIndex = position106, tokenIndex106
				}
			l107:
				{
					position108, tokenIndex108 := position, tokenIndex
					if c := buffer[position]; c < rune('0') || c > rune('7') {
						goto l108
					}
					position++
					goto l109
				l108:
					position, tokenIndex = position108, tokenIndex108
				}
			l109:
				add(ruleOctalEscape, position105)
			}
			return true
		l104:
			position, tokenIndex = position104, tokenIndex104
			return false
		},
		/* 21 HexEscape <- <('\\' 'x' HexDigit+)> */
		func() bool {
			position110, tokenIndex110 := position, tokenIndex
			{
				position111 := position
				if buffer[position] != rune('\\') {
					goto l110
				}
				position++
				if buffer[position] != rune('x') {
					goto l110
				}
				position++
				if !_rules[ruleHexDigit]() {
					goto l110
				}
			l112:
				{
					position113, tokenIndex113 := position, tokenIndex
					if !_rules[ruleHexDigit]() {
						goto l113
					}
					goto l112
				l113:
					position, tokenIndex = position113, tokenIndex113
				}
				add(ruleHexEscape, position111)
			}
			return true
		l110:
			position, tokenIndex = position110, tokenIndex110
			return false
		},
		/* 22 HexDigit <- <([a-f] / [A-F] / [0-9])> */
		func() bool {
			position114, tokenIndex114 := position, tokenIndex
			{
				position115 := position
				{
					position116, tokenIndex116 := position, tokenIndex
					if c := buffer[position]; c < rune('a') || c > rune('f') {
						goto l117
					}
					position++
					goto l116
				l117:
					position, tokenIndex = position116, tokenIndex116
					if c := buffer[position]; c < rune('A') || c > rune('F') {
						goto l118
					}
					position++
					goto l116
				l118:
					position, tokenIndex = position116, tokenIndex116
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l114
					}
					position++
				}
			l116:
				add(ruleHexDigit, position115)
			}
			return true
		l114:
			position, tokenIndex = position114, tokenIndex114
			return false
		},
		/* 23 NumLiteral <- <((Digits '.' Digits?) / Digits)> */
		func() bool {
			position119, tokenIndex119 := position, tokenIndex
			{
				position120 := position
				{
					position121, tokenIndex121 := position, tokenIndex
					if !_rules[ruleDigits]() {
						goto l122
					}
					if buffer[position] != rune('.') {
						goto l122
					}
					position++
					{
						position123, tokenIndex123 := position, tokenIndex
						if !_rules[ruleDigits]() {
							goto l123
						}
						goto l124
					l123:
						position, tokenIndex = position123, tokenIndex123
					}
				l124:
					goto l121
				l122:
					position, tokenIndex = position121, tokenIndex121
					if !_rules[ruleDigits]() {
						goto l119
					}
				}
			l121:
				add(ruleNumLiteral, position120)
			}
			return true
		l119:
			position, tokenIndex = position119, tokenIndex119
			return false
		},
		/* 24 Digits <- <([0-9] ('_'* [0-9])*)> */
		func() bool {
			position125, tokenIndex125 := position, tokenIndex
			{
				position126 := position
				if c := buffer[position]; c < rune('0') || c > rune('9') {
					goto l125
				}
				position++
			l127:
				{
					position128, tokenIndex128 := position, tokenIndex
				l129:
					{
						position130, tokenIndex130 := position, tokenIndex
						if buffer[position] != rune('_') {
							goto l130
						}
						position++
						goto l129
					l130:
						position, tokenIndex = position130, tokenIndex130
					}
					if c := buffer[position]; c < rune('0') || c > rune('9') {
						goto l128
					}
					position++
					goto l127
				l128:
					position, tokenIndex = position128, tokenIndex128
				}
				add(ruleDigits, position126)
			}
			return true
		l125:
			position, tokenIndex = position125, tokenIndex125
			return false
		},
		/* 25 NOT <- <('N' 'O' 'T' Spacing)> */
		func() bool {
			position131, tokenIndex131 := position, tokenIndex
			{
				position132 := position
				if buffer[position] != rune('N') {
					goto l131
				}
				position++
				if buffer[position] != rune('O') {
					goto l131
				}
				position++
				if buffer[position] != rune('T') {
					goto l131
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l131
				}
				add(ruleNOT, position132)
			}
			return true
		l131:
			position, tokenIndex = position131, tokenIndex131
			return false
		},
		/* 26 AND <- <('A' 'N' 'D' Spacing)> */
		func() bool {
			position133, tokenIndex133 := position, tokenIndex
			{
				position134 := position
				if buffer[position] != rune('A') {
					goto l133
				}
				position++
				if buffer[position] != rune('N') {
					goto l133
				}
				position++
				if buffer[position] != rune('D') {
					goto l133
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l133
				}
				add(ruleAND, position134)
			}
			return true
		l133:
			position, tokenIndex = position133, tokenIndex133
			return false
		},
		/* 27 OR <- <('O' 'R' Spacing)> */
		func() bool {
			position135, tokenIndex135 := position, tokenIndex
			{
				position136 := position
				if buffer[position] != rune('O') {
					goto l135
				}
				position++
				if buffer[position] != rune('R') {
					goto l135
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l135
				}
				add(ruleOR, position136)
			}
			return true
		l135:
			position, tokenIndex = position135, tokenIndex135
			return false
		},
		/* 28 EQ <- <('e' 'q' Spacing)> */
		func() bool {
			position137, tokenIndex137 := position, tokenIndex
			{
				position138 := position
				if buffer[position] != rune('e') {
					goto l137
				}
				position++
				if buffer[position] != rune('q') {
					goto l137
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l137
				}
				add(ruleEQ, position138)
			}
			return true
		l137:
			position, tokenIndex = position137, tokenIndex137
			return false
		},
		/* 29 NE <- <('n' 'e' Spacing)> */
		func() bool {
			position139, tokenIndex139 := position, tokenIndex
			{
				position140 := position
				if buffer[position] != rune('n') {
					goto l139
				}
				position++
				if buffer[position] != rune('e') {
					goto l139
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l139
				}
				add(ruleNE, position140)
			}
			return true
		l139:
			position, tokenIndex = position139, tokenIndex139
			return false
		},
		/* 30 LT <- <('l' 't' Spacing)> */
		func() bool {
			position141, tokenIndex141 := position, tokenIndex
			{
				position142 := position
				if buffer[position] != rune('l') {
					goto l141
				}
				position++
				if buffer[position] != rune('t') {
					goto l141
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l141
				}
				add(ruleLT, position142)
			}
			return true
		l141:
			position, tokenIndex = position141, tokenIndex141
			return false
		},
		/* 31 GT <- <('g' 't' Spacing)> */
		func() bool {
			position143, tokenIndex143 := position, tokenIndex
			{
				position144 := position
				if buffer[position] != rune('g') {
					goto l143
				}
				position++
				if buffer[position] != rune('t') {
					goto l143
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l143
				}
				add(ruleGT, position144)
			}
			return true
		l143:
			position, tokenIndex = position143, tokenIndex143
			return false
		},
		/* 32 LTE <- <('l' 't' 'e' Spacing)> */
		func() bool {
			position145, tokenIndex145 := position, tokenIndex
			{
				position146 := position
				if buffer[position] != rune('l') {
					goto l145
				}
				position++
				if buffer[position] != rune('t') {
					goto l145
				}
				position++
				if buffer[position] != rune('e') {
					goto l145
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l145
				}
				add(ruleLTE, position146)
			}
			return true
		l145:
			position, tokenIndex = position145, tokenIndex145
			return false
		},
		/* 33 GTE <- <('g' 't' 'e' Spacing)> */
		func() bool {
			position147, tokenIndex147 := position, tokenIndex
			{
				position148 := position
				if buffer[position] != rune('g') {
					goto l147
				}
				position++
				if buffer[position] != rune('t') {
					goto l147
				}
				position++
				if buffer[position] != rune('e') {
					goto l147
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l147
				}
				add(ruleGTE, position148)
			}
			return true
		l147:
			position, tokenIndex = position147, tokenIndex147
			return false
		},
		/* 34 BTW <- <('b' 't' 'w' Spacing)> */
		func() bool {
			position149, tokenIndex149 := position, tokenIndex
			{
				position150 := position
				if buffer[position] != rune('b') {
					goto l149
				}
				position++
				if buffer[position] != rune('t') {
					goto l149
				}
				position++
				if buffer[position] != rune('w') {
					goto l149
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l149
				}
				add(ruleBTW, position150)
			}
			return true
		l149:
			position, tokenIndex = position149, tokenIndex149
			return false
		},
		/* 35 STW <- <('s' 't' 'w' Spacing)> */
		func() bool {
			position151, tokenIndex151 := position, tokenIndex
			{
				position152 := position
				if buffer[position] != rune('s') {
					goto l151
				}
				position++
				if buffer[position] != rune('t') {
					goto l151
				}
				position++
				if buffer[position] != rune('w') {
					goto l151
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l151
				}
				add(ruleSTW, position152)
			}
			return true
		l151:
			position, tokenIndex = position151, tokenIndex151
			return false
		},
		/* 36 CTN <- <('c' 't' 'n' Spacing)> */
		func() bool {
			position153, tokenIndex153 := position, tokenIndex
			{
				position154 := position
				if buffer[position] != rune('c') {
					goto l153
				}
				position++
				if buffer[position] != rune('t') {
					goto l153
				}
				position++
				if buffer[position] != rune('n') {
					goto l153
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l153
				}
				add(ruleCTN, position154)
			}
			return true
		l153:
			position, tokenIndex = position153, tokenIndex153
			return false
		},
		/* 37 LBRK <- <('[' Spacing)> */
		func() bool {
			position155, tokenIndex155 := position, tokenIndex
			{
				position156 := position
				if buffer[position] != rune('[') {
					goto l155
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l155
				}
				add(ruleLBRK, position156)
			}
			return true
		l155:
			position, tokenIndex = position155, tokenIndex155
			return false
		},
		/* 38 RBRK <- <(']' Spacing)> */
		func() bool {
			position157, tokenIndex157 := position, tokenIndex
			{
				position158 := position
				if buffer[position] != rune(']') {
					goto l157
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l157
				}
				add(ruleRBRK, position158)
			}
			return true
		l157:
			position, tokenIndex = position157, tokenIndex157
			return false
		},
		/* 39 LPAR <- <('(' Spacing)> */
		func() bool {
			position159, tokenIndex159 := position, tokenIndex
			{
				position160 := position
				if buffer[position] != rune('(') {
					goto l159
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l159
				}
				add(ruleLPAR, position160)
			}
			return true
		l159:
			position, tokenIndex = position159, tokenIndex159
			return false
		},
		/* 40 RPAR <- <(')' Spacing)> */
		func() bool {
			position161, tokenIndex161 := position, tokenIndex
			{
				position162 := position
				if buffer[position] != rune(')') {
					goto l161
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l161
				}
				add(ruleRPAR, position162)
			}
			return true
		l161:
			position, tokenIndex = position161, tokenIndex161
			return false
		},
		/* 41 COMMA <- <(',' Spacing)> */
		func() bool {
			position163, tokenIndex163 := position, tokenIndex
			{
				position164 := position
				if buffer[position] != rune(',') {
					goto l163
				}
				position++
				if !_rules[ruleSpacing]() {
					goto l163
				}
				add(ruleCOMMA, position164)
			}
			return true
		l163:
			position, tokenIndex = position163, tokenIndex163
			return false
		},
		/* 42 Spacing <- <(' ' / '\t')*> */
		func() bool {
			{
				position166 := position
			l167:
				{
					position168, tokenIndex168 := position, tokenIndex
					{
						position169, tokenIndex169 := position, tokenIndex
						if buffer[position] != rune(' ') {
							goto l170
						}
						position++
						goto l169
					l170:
						position, tokenIndex = position169, tokenIndex169
						if buffer[position] != rune('\t') {
							goto l168
						}
						position++
					}
				l169:
					goto l167
				l168:
					position, tokenIndex = position168, tokenIndex168
				}
				add(ruleSpacing, position166)
			}
			return true
		},
		/* 43 EOT <- <!.> */
		func() bool {
			position171, tokenIndex171 := position, tokenIndex
			{
				position172 := position
				{
					position173, tokenIndex173 := position, tokenIndex
					if !matchDot() {
						goto l173
					}
					goto l171
				l173:
					position, tokenIndex = position173, tokenIndex173
				}
				add(ruleEOT, position172)
			}
			return true
		l171:
			position, tokenIndex = position171, tokenIndex171
			return false
		},
		nil,
	}
	p.rules = _rules
	return nil
}
