// Package http provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package http

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// CreateSobRequest defines model for CreateSobRequest.
type CreateSobRequest struct {
	Description string `json:"Description"`
	Id          string `json:"Id"`
	Name        string `json:"Name"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// SobResponse defines model for SobResponse.
type SobResponse struct {
	Description string `json:"Description"`
	Id          string `json:"Id"`
	Name        string `json:"Name"`
}

// SobsResponse defines model for SobsResponse.
type SobsResponse []SobResponse

// CreateJSONBody defines parameters for Create.
type CreateJSONBody CreateSobRequest

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody CreateJSONBody
